---
title: "enzyme activity"
author: "Colleen Cosgrove"
date: "December 3, 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load data}
## Load decomp and soil data
decomp.dat=read.csv("decomprawdata.csv",header = TRUE)
names(decomp.dat)[names(decomp.dat)=="ï..Bag.ID"]<-"Bag.ID"
decomp.samp=read.csv("decompsampleplots.csv",header=TRUE)
names(decomp.samp)[names(decomp.samp)=="ï..Bag.ID"]<-"Bag.ID"
#add plot and ecosystem type in for each of the samples bags
decomp.dat=merge(decomp.samp,decomp.dat)
soil.dat=read.csv("C:/Users/crc31/OneDrive/Documents/School/Grad School/SpatialStats/soil data May 08 for tree plots.csv", header=T)
plotdesig=read.csv("plotdesignations.csv")

#merge decomp and soil data
decomp.dat=merge(decomp.dat,soil.dat)
dim(decomp.dat)
decomp.dat=decomp.dat[!is.na(decomp.dat$Time.mo),]
decomp.dat=droplevels(decomp.dat)

###############
## Load enzyme activity data
hydroact.dat=read.csv("DataTxtFiles/enzymeactivity.csv",header=TRUE)
dopaact.dat=read.csv("DataTxtFiles/dopaenzymeactivity.csv", header=TRUE)

## Log transform enzyme activity data
#First, make all negative activities 1 so that the log(1)=0. We will run all stats on log activity, so this will fix errors associated with created "Inf" or "NaN"s
colnames(hydroact.dat)
hydroact.dat$activity[hydroact.dat$activity<1]<-01
dopaact.dat$activity[dopaact.dat$activity<1]<-01
#Take the log of the variables. Note: there's lots of previously neg numbers and really low values in dopa activity. That means we're gonna get a lot of neg and really low log numbers.
hydroact.dat$activity.lg=log(as.numeric(as.character(hydroact.dat$activity)))
dopaact.dat$activity.lg=log(as.numeric(as.character(dopaact.dat$activity)))
##One value in the abova DOPA code refuses to change to a 1 which is weird AF. Anyway. We'll just cut it out later. Fuck it.

#merge enzyme and site data
hydroact.dat=merge(hydroact.dat,decomp.samp,by="Bag.ID")
hydroact.dat=merge(hydroact.dat,soil.dat)
dopaact.dat=merge(dopaact.dat,decomp.samp,by="Bag.ID")
dopaact.dat=merge(dopaact.dat,soil.dat)
```

```{r load packages}
library(ggplot2)
library(nlme)
library(lme4)
library(glmm)
library(vegan)
library(emmeans)
library(dplyr)
```

```{r decay rate K}
#remove rows that are 0 for PropInitial - creates NANs in the log tranformation, otherwise and we can't use those.
decomp.dat=subset(decomp.dat,as.numeric(as.character(decomp.dat$PropInitial)) > 0)
decomp.dat.rate=decomp.dat[decomp.dat$Harvest!="H0",]
decomp.dat.rate=droplevels(decomp.dat.rate)

#subset the data by Species
decomp.dat.rate.acesac=decomp.dat.rate[decomp.dat.rate$Species=="ACESAC",]

# First order decay rate model
decompk.acesac=matrix(nrow=66,ncol=1)
decay.k.meta.acesac=matrix(nrow=66,ncol=2)

m=1

for(k in c("2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","22","23","24","A1/2","A3/4","A5/6","B1/2","B3/4","B5/6","D1/2","D3/4","D5/6","E1/2","E3/4","E5/6","G1/2","G3/4","G5/6","H1/2","H3/4","H5/6","I1/2","I3/4","I6","J1/2","J3/4","J5/6","K1/2","K3/4","K5/6","L1/2","L3/4","L5/6","P1/2","P3/4","P5/6","Q1/2","Q3/4","Q5/6","R1","R2","R4","R5","S1","S2","S4","S5")){
      decomp.dat.acesac.k=decomp.dat.rate.acesac[decomp.dat.rate.acesac$Plot==k,]
      reg.k=lm(log(as.numeric(as.character(decomp.dat.acesac.k$PropInitial)))~0+Time.mo, data=decomp.dat.acesac.k)
      decompk.acesac[m]=as.numeric(reg.k$coefficients)
      decay.k.meta.acesac[m,1]="ACESAC"
      decay.k.meta.acesac[m,2]=k
      m=m+1
}

decompk.acesac
decay.k.meta.acesac
decay.k.data.acesac=as.data.frame(cbind(decay.k.meta.acesac,decompk.acesac))
colnames(decay.k.data.acesac)=c("Species","Plot","decompk")
decay.k.data.acesac

###CAROVA
decomp.dat.rate.carova=decomp.dat.rate[decomp.dat.rate$Species=="CAROVA",]

decompk.carova=matrix(nrow=65,ncol=1)
decay.k.meta.carova=matrix(nrow=65,ncol=2)

m=1

for(k in c("2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","22","23","24","A1/2","A3/4","A5/6","B1/2","B3/4","B5/6","D1/2","D3/4","D5/6","E1/2","E3/4","E5/6","G1/2","G3/4","G5/6","H1/2","H3/4","H5/6","I1/2","I3/4","I6","J1/2","J3/4","J5/6","K1/2","K3/4","K5/6","L1/2","L3/4","L5/6","P1/2","P3/4","P5/6","Q1/2","Q3/4","Q5/6","R1","R2","R4","R5","S1","S4","S5")){
      decomp.dat.carova.k=decomp.dat.rate.carova[decomp.dat.rate.carova$Plot==k,]
      reg.k=lm(log(as.numeric(as.character(decomp.dat.carova.k$PropInitial)))~0+Time.mo, data=decomp.dat.carova.k)
      decompk.carova[m]=as.numeric(reg.k$coefficients)
      decay.k.meta.carova[m,1]="CAROVA"
      decay.k.meta.carova[m,2]=k
      m=m+1
}

decompk.carova
decay.k.meta.carova
decay.k.data.carova<-as.data.frame(cbind(decay.k.meta.carova,decompk.carova))
colnames(decay.k.data.carova)=c("Species","Plot","decompk")
decay.k.data.carova

####QUERUB
decomp.dat.rate.querub=decomp.dat.rate[decomp.dat.rate$Species=="QUERUB",]

decompk.querub=matrix(nrow=68,ncol=1)
decay.k.meta.querub=matrix(nrow=68,ncol=2)

m=1

for(k in c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","A1/2","A3/4","A5/6","B1/2","B3/4","B5/6","D1/2","D3/4","D5/6","E1/2","E3/4","E5/6","G1/2","G3/4","G5/6","H1/2","H3/4","H5/6","I1/2","I3/4","I6","J1/2","J3/4","J5/6","K1/2","K3/4","K5/6","L1/2","L3/4","L5/6","P1/2","P3/4","P5/6","Q1/2","Q3/4","Q5/6","R1","R2","R4","R5","S1","S2","S4","S5")){
      decomp.dat.querub.k=decomp.dat.rate[decomp.dat.rate.querub$Plot==k,]
      reg.k=lm(log(as.numeric(as.character(decomp.dat.querub.k$PropInitial)))~0+Time.mo, data=decomp.dat.querub.k)
      decompk.querub[m]=as.numeric(reg.k$coefficients)
      decay.k.meta.querub[m,1]="QUERUB"
      decay.k.meta.querub[m,2]=k
      #decay.k.meta[m,3]=as.character(decomp.dat.rate.k$Bag.ID[1])
      m=m+1
}

decompk.querub
decay.k.meta.querub
decay.k.data.querub=as.data.frame(cbind(decay.k.meta.querub,decompk.querub))
colnames(decay.k.data.querub)=c("Species","Plot","decompk")
decay.k.data.querub

##merge all of these together so they're all accessible.
decompk.allspec.row=data.frame(nrow=199, ncol=3)
decompk.allspec.row=rbind(decay.k.data.acesac,decay.k.data.carova,decay.k.data.querub)
decompk.allspec.row

decompk.row.soil=merge(decompk.allspec.row,soil.dat,by="Plot")

#uneven number of rows, so can't use cbind.
decompk.allspec.col=data.frame(ncol=65, ncol=5)
decomp.k.data.acesac=decay.k.data.acesac[decay.k.data.acesac$Plot!="S2",]
decomp.k.data.querub=decay.k.data.querub[decay.k.data.querub$Plot!="1",]
decomp.k.data.querub=decomp.k.data.querub[decomp.k.data.querub$Plot!="21",]
decomp.k.data.querub=decomp.k.data.querub[decomp.k.data.querub$Plot!="S2",]
decompk.allspec.col=cbind(decomp.k.data.acesac,decay.k.data.carova,decomp.k.data.querub)
decompk.allspec.col
decompk.allspec.col=decompk.allspec.col[,c(1:4,6:7,9)]
colnames(decompk.allspec.col)=c("acesac","Plot","decompk.acesac","carova","decompk.carova","querub","decompk.querub")
decompk.allspec.col=decompk.allspec.col[1:64,]
```

```{r date collected}
#check to make sure there are no significant differences between dates collected within harvests.
#subsetdata
collection1=decomp.dat[decomp.dat$Harvest=="H1",]
collection1=droplevels(collection1)
collection2=decomp.dat[decomp.dat$Harvest=="H2",]
collection2=droplevels(collection2)
collection3=decomp.dat[decomp.dat$Harvest=="H3",]
collection3=droplevels(collection3)

#Harvest 1
collection1$PropInitial=as.numeric(as.character(collection1$PropInitial))
logitTransformation=function(p){ log(p/(1-p))}
collection1$PropInitial=logitTransformation(collection1$PropInitial)
harv1=aov(collection1$PropInitial~collection1$Date.Collected)
summary(harv1)
TukeyHSD(harv1)
boxplot(collection1$PropInitial~collection1$Date.Collected)
shapiro.test(collection1$PropInitial)
hist(collection1$PropInitial)
#collection1=na.omit(collection1)

harv1.l=lme(PropInitial~Date.Collected, random=~1|TerrType, data=na.omit(collection1))
anova(harv1.l)

#Harvest 2
harv2=aov(as.numeric(as.character(collection2$PropInitial))~collection2$Date.Collected)
summary(harv2)
#plot(as.numeric(as.character(collection2$PropInitial))~collection2$Date.Collected)

#Harvest 3
harv3=aov(as.numeric(as.character(collection3$PropInitial))~collection3$Date.Collected)
summary(harv3)
#plot(as.numeric(as.character(collection3$PropInitial))~collection3$Date.Collected)
```
```{r mass loss linear regressions}
## To test H1 - Decomposition rates will be slower in ecotones than in ecosystem cores. 
####Subset and prep the data####
#merge the decompk.row.soil dataset with the plot design. Using the row dataset (not column), we can compare decay rates across species as well as between.
decompk.row.desig=merge(decompk.row.soil,plotdesig)
decompk.row.desig=decompk.row.desig[decompk.row.desig$TerrType!="S",]
dim(decompk.row.desig)
colnames(decompk.row.desig)
#Take out the chunks the TerrTypes that only have one plot and, thus, aren't going to be usable.
decompk.row.desig=decompk.row.desig[decompk.row.desig$TerrType=="R"|decompk.row.desig$TerrType=="RU"|decompk.row.desig$TerrType=="T-UR"|decompk.row.desig$TerrType=="UR"|decompk.row.desig$TerrType=="U"|decompk.row.desig$TerrType=="UB"|decompk.row.desig$TerrType=="T-UB"|decompk.row.desig$TerrType=="BU"|decompk.row.desig$TerrType=="B"|decompk.row.desig$TerrType=="BR"|decompk.row.desig$TerrType=="T-RB"|decompk.row.desig$TerrType=="RB",]

## decomp by terr type with plot as a random effect
massloss.m1=lme(as.numeric(as.character(decompk))~TerrType,random=~1|Plot, data=decompk.row.desig)
summary(massloss.m1)
#Nothing looks significant in the entire model. But let's look at species.
massloss.sp=lme(as.numeric(as.character(decompk))~TerrType*Species,random=~1|Plot, data=decompk.row.desig)
summary(massloss.sp)
anova(massloss.sp)
#SO many more effects. Let's break this down into smaller tests so we can actually look at it.

#Subset the data into transect types (e.g., B-U, R-U and R-B)
#by transect types (e.g. R->U)
decompk.row.ripup=decompk.row.desig[decompk.row.desig$TerrType=="R"|decompk.row.desig$TerrType=="RU"|decompk.row.desig$TerrType=="T-UR"|decompk.row.desig$TerrType=="UR"|decompk.row.desig$TerrType=="U",]
decompk.row.botup=decompk.row.desig[decompk.row.desig$TerrType=="B"|decompk.row.desig$TerrType=="BU"|decompk.row.desig$TerrType=="T-UB"|decompk.row.desig$TerrType=="UB"|decompk.row.desig$TerrType=="U",]
decompk.row.ripbot=decompk.row.desig[decompk.row.desig$TerrType=="R"|decompk.row.desig$TerrType=="RB"|decompk.row.desig$TerrType=="T-RB"|decompk.row.desig$TerrType=="BR"|decompk.row.desig$TerrType=="B",]

#Split these transect types into individual species
decompk.row.ripup.acesac=decompk.row.ripup[decompk.row.ripup$Species=="ACESAC",]
decompk.row.ripup.carova=decompk.row.ripup[decompk.row.ripup$Species=="CAROVA",]
decompk.row.ripup.querub=decompk.row.ripup[decompk.row.ripup$Species=="QUERUB",]
decompk.row.botup.acesac=decompk.row.botup[decompk.row.botup$Species=="ACESAC",]
decompk.row.botup.carova=decompk.row.botup[decompk.row.botup$Species=="CAROVA",]
decompk.row.botup.querub=decompk.row.botup[decompk.row.botup$Species=="QUERUB",]
decompk.row.ripbot.acesac=decompk.row.ripbot[decompk.row.ripbot$Species=="ACESAC",]
decompk.row.ripbot.carova=decompk.row.ripbot[decompk.row.ripbot$Species=="CAROVA",]
decompk.row.ripbot.querub=decompk.row.ripbot[decompk.row.ripbot$Species=="QUERUB",]

## decomp by terr type and plot WITHIN transect types
####Riparian to Upland transect####
massloss.ripup=lme(as.numeric(as.character(decompk))~TerrType,random=~1|Plot, data=decompk.row.ripup)
summary(massloss.ripup) #Nothing significant

#And again with species as an intercept
massloss.ripup.sp=lme(as.numeric(as.character(decompk))~TerrType*Species,random=~1|Plot, data=decompk.row.ripup)
anova(massloss.ripup.sp)
emmeans(massloss.ripup.sp, pairwise~TerrType*Species)

#Order the transect logically
decompk.row.ripup$TerrType=factor(decompk.row.ripup$TerrType, levels=c("R","RU","T-UR","UR","U"))
decompk.row.ripup$Species=factor(decompk.row.ripup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#calculate average
#gd= decompk.row.ripup %>%
  #group_by(Species, TerrType) %>%
  #summarise(mean=mean(as.numeric(as.character(decompk))))%>%
  #arrange(desc(Species,TerrType))

#plot. Gotta think about the best way to display these data.
ggplot(decompk.row.ripup, aes(x=TerrType,y=as.numeric(as.character(decompk)),colour=Species,group=Species))+
  geom_point(position=position_dodge(0.5), size=3)+
  ggtitle("RipUp TerrTypexSpecies")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=18),
        axis.title=element_text(size=18))+
  ylab("Decay K")+
  scale_y_continuous(limits=c(-6.5,0))+
  stat_summary(fun="mean", geom="point",position=position_dodge(0.5), size=6)
#box plots
ggplot(decompk.row.ripup, aes(x=TerrType,y=as.numeric(as.character(decompk)),colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  ggtitle("RipUp TerrTypexSpecies")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=18),
        axis.title=element_text(size=18))+
  ylab("Decay K")+
  scale_y_continuous(limits=c(-6.5,0))

####Bottomland-upland transect####
massloss.botup=lme(as.numeric(as.character(decompk))~TerrType,random=~1|Plot, data=decompk.row.botup)
anova(massloss.botup) #Nothing significant

massloss.botup.sp=lme(as.numeric(as.character(decompk))~TerrType*Species,random=~1|Plot, data=decompk.row.botup)
anova(massloss.botup.sp)
emmeans(massloss.botup.sp, pairwise~TerrType*Species)

#Order the transect logically
decompk.row.botup$TerrType=factor(decompk.row.botup$TerrType, levels=c("B","BU","T-UB","UB","U"))
decompk.row.botup$Species=factor(decompk.row.botup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#Plot.
ggplot(decompk.row.botup, aes(x=TerrType,y=as.numeric(as.character(decompk)),colour=Species,group=Species))+
  geom_point(position=position_dodge(0.5), size=4)+
  ggtitle("BotUp TerrTypexSpecies")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=18),
        axis.title=element_text(size=18))+
  ylab("Decay K")+
  scale_y_continuous(limits=c(-6.5,0))+
  stat_summary(fun="mean", geom="point",position=position_dodge(0.5), size=6)
#Box plot
ggplot(decompk.row.botup, aes(x=TerrType,y=as.numeric(as.character(decompk)),colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  ggtitle("BotUp TerrTypexSpecies")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=18),
        axis.title=element_text(size=18))+
  ylab("Decay K")+
  scale_y_continuous(limits=c(-6.5,0))

####Riparian-bottomland transect####
massloss.ripbot=lme(as.numeric(as.character(decompk))~TerrType,random=~1|Plot, data=decompk.row.ripbot)
anova(massloss.ripbot) #Nothing significant

massloss.ripbot.sp=lme(as.numeric(as.character(decompk))~TerrType*Species,random=~1|Plot, data=decompk.row.ripbot)
anova(massloss.ripbot.sp)
emmeans(massloss.ripbot.sp, pairwise~Species)

#Order the transect accordingly
decompk.row.ripbot$TerrType=factor(decompk.row.ripbot$TerrType, levels=c("R", "RB","T-RB","BR","B"))
decompk.row.ripbot$Species=factor(decompk.row.ripbot$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#Plot
ggplot(decompk.row.ripbot, aes(x=TerrType,y=as.numeric(as.character(decompk)),colour=Species,group=Species))+
  geom_point(position=position_dodge(0.5), size=4)+
  ggtitle("RipBot TerrTypexSpecies")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=18),
        axis.title=element_text(size=18))+
  ylab("Decay K")+
  scale_y_continuous(limits=c(-6.5,0))+
  stat_summary(fun="mean", geom="point",position=position_dodge(0.5), size=6)
#Box plots
ggplot(decompk.row.ripbot, aes(x=TerrType,y=as.numeric(as.character(decompk)),colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  ggtitle("RipBot TerrTypexSpecies")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=18),
        axis.title=element_text(size=18))+
  ylab("Decay K")+
  scale_y_continuous(limits=c(-6.5,0))
```
```{linear model with TerrType single species}
####Riparian to Upland Transect####
##ACESAC
massloss.ripup.acesac=lme(as.numeric(as.character(decompk))~TerrType,random=~1|Plot, data=decompk.row.ripup.acesac)
anova(massloss.ripup.acesac)
##CAROVA
massloss.ripup.carova=lme(as.numeric(as.character(decompk))~TerrType,random=~1|Plot, data=decompk.row.ripup.carova)
anova(massloss.ripup.carova)
##QUERUB
massloss.ripup.querub=lme(as.numeric(as.character(decompk))~TerrType,random=~1|Plot, data=decompk.row.ripup.querub)
anova(massloss.ripup.querub)
####Bottomland to Upland Transect####
##ACESAC
massloss.botup.acesac=lme(as.numeric(as.character(decompk))~TerrType,random=~1|Plot, data=decompk.row.botup.acesac)
anova(massloss.botup.acesac)
emmeans(massloss.botup.acesac, pairwise~TerrType)
##CAROVA
massloss.botup.carova=lme(as.numeric(as.character(decompk))~TerrType,random=~1|Plot, data=decompk.row.botup.carova)
anova(massloss.botup.carova)
##QUERUB
massloss.botup.querub=lme(as.numeric(as.character(decompk))~TerrType,random=~1|Plot, data=decompk.row.botup.querub)
anova(massloss.botup.querub)
####Riparian to Bottomland Transect####
##ACESAC
massloss.ripbot.acesac=lme(as.numeric(as.character(decompk))~TerrType,random=~1|Plot, data=decompk.row.ripbot.acesac)
anova(massloss.ripbot.acesac)
##CAROVA
massloss.ripbot.carova=lme(as.numeric(as.character(decompk))~TerrType,random=~1|Plot, data=decompk.row.ripbot.carova)
anova(massloss.ripbot.carova)
##QUERUB
massloss.ripbot.querub=lme(as.numeric(as.character(decompk))~TerrType,random=~1|Plot, data=decompk.row.ripbot.querub)
anova(massloss.ripbot.querub)
```

```{r linear model with Terr Type LUMPED TRANS}
#Remove S as a Lumped Trans variable because we don't need that.
decompk.row.desig=decompk.row.desig[decompk.row.desig$LumpedTrans!="S",]

## decomp by terr type and plot WITHIN transect types
massloss.lumped=lme(as.numeric(as.character(decompk))~LumpedTrans,random=~1|Plot, data=decompk.row.desig)
anova(massloss.lumped)
summary(massloss.lumped)
#And add species into the model
massloss.lumped.sp=lme(as.numeric(as.character(decompk))~LumpedTrans*Species,random=~1|Plot, data=decompk.row.desig)
summary(massloss.lumped.sp)
anova(massloss.lumped.sp)
emmeans(massloss.lumped.sp,pairwise~LumpedTrans*Species)
#Way more to break apart. Let's do one transect at a time.

#We can use the subsetted dataframes from earlier and just change the TerrType variable to the LumpedTrans variable.
####Riparian to Upland transect####
massloss.ripup.lt=lme(as.numeric(as.character(decompk))~LumpedTrans,random=~1|Plot, data=decompk.row.ripup)
anova(massloss.ripup.lt)
summary(massloss.ripup.lt) #Some Significance

#And again with species as an intercept
massloss.ripup.splt=lme(as.numeric(as.character(decompk))~LumpedTrans*Species,random=~1|Plot, data=decompk.row.ripup)
anova(massloss.ripup.splt)
summary(massloss.ripup.splt) #Lots of significance
emmeans(massloss.ripup.splt, pairwise ~ LumpedTrans*Species)

#Order the transect logically
decompk.row.ripup$LumpedTrans=factor(decompk.row.ripup$LumpedTrans, levels=c("R","UR","U"))
decompk.row.ripup$Species=factor(decompk.row.ripup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot. Gotta think about the best way to display these data.
ggplot(decompk.row.ripup, aes(x=LumpedTrans,y=as.numeric(as.character(decompk)),colour=Species,group=Species))+
  geom_point(position=position_dodge(0.5), size=4)+
  ggtitle("RipUp TerrTypexSpecies")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=18),
        axis.title=element_text(size=18))+
  ylab("Decay K")+
  scale_y_continuous(limits=c(-6.5,0))+
  stat_summary(fun="mean", geom="point",position=position_dodge(0.5), size=6)
#Box plots
ggplot(decompk.row.ripup, aes(x=Species,y=as.numeric(as.character(decompk)),colour=LumpedTrans))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("RipUp TerrTypexSpecies")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        axis.title.x=element_blank(),
        legend.position=c("right")
        )+
  ylab("Decay K")+
  scale_y_continuous(limits=c(-6.5,0))

####Bottomland-upland transect####
massloss.botup.lt=lme(as.numeric(as.character(decompk))~LumpedTrans,random=~1|Plot, data=decompk.row.botup)
anova(massloss.botup.lt)
summary(massloss.botup.lt) #Nothing significant

massloss.botup.splt=lme(as.numeric(as.character(decompk))~LumpedTrans*Species,random=~1|Plot, data=decompk.row.botup)
summary(massloss.botup.splt) #Lots of significance
anova(massloss.botup.splt)
emmeans(massloss.botup.splt, pairwise ~ LumpedTrans*Species)

#Order the transect logically
decompk.row.botup$LumpedTrans=factor(decompk.row.botup$LumpedTrans, levels=c("B","UB","U"))
decompk.row.botup$Species=factor(decompk.row.botup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#Plot.
ggplot(decompk.row.botup, aes(x=LumpedTrans,y=as.numeric(as.character(decompk)),colour=Species,group=Species))+
  geom_point(position=position_dodge(0.5), size=4)+
  ggtitle("BotUp LumpedTransxSpecies")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=18),
        axis.title=element_text(size=18))+
  ylab("Decay K")+
  scale_y_continuous(limits=c(-6.5,0))+
  stat_summary(fun="mean", geom="point",position=position_dodge(0.5), size=6)
#Box plot
ggplot(decompk.row.botup, aes(x=Species,y=as.numeric(as.character(decompk)),colour=LumpedTrans))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("BotUp TerrTypexSpecies")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "right"
        )+
  ylab("Decay K")+
  scale_y_continuous(limits=c(-6.5,0))

####Riparian-bottomland transect####
massloss.ripbot.lt=lme(as.numeric(as.character(decompk))~LumpedTrans,random=~1|Plot, data=decompk.row.ripbot)
summary(massloss.ripbot.lt) #Nothing significant

massloss.ripbot.splt=lme(as.numeric(as.character(decompk))~LumpedTrans*Species,random=~1|Plot, data=decompk.row.ripbot)
anova(massloss.ripbot.splt)
summary(massloss.ripbot.splt) #Only a few things are significant
emmeans(massloss.ripbot.splt,pairwise ~ Species)
emmeans(massloss.ripbot.splt, pairwise ~ LumpedTrans*Species)

#Order the transect accordingly
decompk.row.ripbot$LumpedTrans=factor(decompk.row.ripbot$LumpedTrans, levels=c("R", "RB","B"))
decompk.row.ripbot$Species=factor(decompk.row.ripbot$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#Plot
ggplot(decompk.row.ripbot, aes(x=LumpedTrans,y=as.numeric(as.character(decompk)),colour=Species,group=Species))+
  geom_point(position=position_dodge(0.5), size=4)+
  ggtitle("RipBot LumpedTransxSpecies")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=18),
        axis.title=element_text(size=18))+
  ylab("Decay K")+
  scale_y_continuous(limits=c(-6.5,0))+
  stat_summary(fun="mean", geom="point",position=position_dodge(0.5), size=6)
#Box plots
ggplot(decompk.row.ripbot, aes(x=Species,y=as.numeric(as.character(decompk)),colour=LumpedTrans))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=40),
        axis.title=element_text(size=30),
        axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Decay K")+
  scale_y_continuous(limits=c(-6.5,0))
```
```{r linear model with Terr Type lumped trans single species}
####Riparian to Upland transect####
##ACESAC
massloss.ripup.acesac.lt=lme(as.numeric(as.character(decompk))~LumpedTrans,random=~1|Plot, data=decompk.row.ripup.acesac)
anova(massloss.ripup.acesac.lt)
emmeans(massloss.ripup.acesac.lt,pairwise~LumpedTrans)
##CAROVA
massloss.ripup.carova.lt=lme(as.numeric(as.character(decompk))~LumpedTrans,random=~1|Plot, data=decompk.row.ripup.carova)
anova(massloss.ripup.carova.lt)
##QUERUB
massloss.ripup.querub.lt=lme(as.numeric(as.character(decompk))~LumpedTrans,random=~1|Plot, data=decompk.row.ripup.querub)
anova(massloss.ripup.querub.lt)
emmeans(massloss.ripup.querub.lt, pairwise~LumpedTrans)

####Bottomland to Upland Transect####
##ACESAC
massloss.botup.acesac.lt=lme(as.numeric(as.character(decompk))~LumpedTrans,random=~1|Plot, data=decompk.row.botup.acesac)
anova(massloss.botup.acesac.lt)
emmeans(massloss.botup.acesac.lt, pairwise~LumpedTrans)
##CAROVA
massloss.botup.carova.lt=lme(as.numeric(as.character(decompk))~LumpedTrans,random=~1|Plot, data=decompk.row.botup.carova)
anova(massloss.botup.carova.lt)
##QUERUB
massloss.botup.querub.lt=lme(as.numeric(as.character(decompk))~LumpedTrans,random=~1|Plot, data=decompk.row.botup.querub)
anova(massloss.botup.querub.lt)
emmeans(massloss.botup.querub.lt, pairwise~LumpedTrans)

####Bottomland to Riparian####
##ACESAC
massloss.ripbot.acesac.lt=lme(as.numeric(as.character(decompk))~LumpedTrans,random=~1|Plot, data=decompk.row.ripbot.acesac)
anova(massloss.ripbot.acesac.lt)
emmeans(massloss.ripbot.acesac.lt, pairwise~LumpedTrans)
##CAROVA
massloss.ripbot.carova.lt=lme(as.numeric(as.character(decompk))~LumpedTrans,random=~1|Plot, data=decompk.row.ripbot.carova)
anova(massloss.ripbot.carova.lt)
##QUERUB
massloss.ripbot.querub.lt=lme(as.numeric(as.character(decompk))~LumpedTrans,random=~1|Plot, data=decompk.row.ripbot.querub)
anova(massloss.ripbot.querub.lt)
```

```{r mixed model decomp to soil}
decompk.row.soil.eco=na.exclude(decompk.row.desig)
decompk.row.soil.eco$decompk=as.numeric(as.character(decompk.row.soil.eco$decompk))
#Long model
decompk.soil.long.mod=lme(decompk~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long,random=~1|Plot, data=decompk.row.soil.eco)
anova(decompk.soil.long.mod)

#Short model
decompk.soil.short.mod=lme(decompk~Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short,random=~1|Plot, data=decompk.row.soil.eco)
anova(decompk.soil.short.mod)

#nug model
decompk.soil.nug.mod=lme(decompk~Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=decompk.row.soil.eco)
anova(decompk.soil.nug.mod)

#Check for an ecosystem effect
decompk.soil.eco.mod = lm(decompk.row.soil.eco$decompk ~ decompk.row.soil.eco$TerrType)
anova(decompk.soil.eco.mod)

###CORE###
decompk.row.soil.eco.core=decompk.row.soil.eco[decompk.row.soil.eco$EP=="Core",]
#Long model
decompk.soil.long.mod=lme(decompk~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long,random=~1|Plot, data=decompk.row.soil.eco)
anova(decompk.soil.long.mod)

#Short model
decompk.soil.short.mod=lme(decompk~Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short,random=~1|Plot, data=decompk.row.soil.eco)
anova(decompk.soil.short.mod)

#nug model
decompk.soil.nug.mod=lme(decompk~Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=decompk.row.soil.eco)
anova(decompk.soil.nug.mod)

#Check for an ecosystem effect
decompk.soil.eco.mod = lm(decompk.row.soil.eco$decompk ~ decompk.row.soil.eco$TerrType)
anova(decompk.soil.eco.mod)

####ACESAC####
decompk.row.soil.eco.as=decompk.row.soil.eco[decompk.row.soil.eco$Species=="ACESAC",]
#Long model
decompk.soil.long.acesac=lme(decompk~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long,random=~1|Plot, data=decompk.row.soil.eco.as)
anova(decompk.soil.long.acesac)

#Short model
decompk.soil.short.acesac=lme(decompk~Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short,random=~1|Plot, data=decompk.row.soil.eco.as)
anova(decompk.soil.short.acesac)

#nug model
decompk.soil.nug.acesac=lme(decompk~Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=decompk.row.soil.eco.as)
anova(decompk.soil.nug.acesac)

#Check for an ecosystem effect
decompk.soil.eco.acesac = lm(decompk.row.soil.eco.as$decompk ~ decompk.row.soil.eco.as$TerrType)
anova(decompk.soil.eco.acesac)

###CORE###
decompk.row.soil.eco.as=decompk.row.soil.eco.as[decompk.row.soil.eco.as$EP=="Core",]
#Long model
decompk.soil.long.acesac=lme(decompk~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long,random=~1|Plot, data=decompk.row.soil.eco.as)
anova(decompk.soil.long.acesac)

#Short model
decompk.soil.short.acesac=lme(decompk~Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short,random=~1|Plot, data=decompk.row.soil.eco.as)
anova(decompk.soil.short.acesac)

#nug model
decompk.soil.nug.acesac=lme(decompk~Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=decompk.row.soil.eco.as)
anova(decompk.soil.nug.acesac)

#Check for an ecosystem effect
decompk.soil.eco.acesac = lm(decompk.row.soil.eco.as$decompk ~ decompk.row.soil.eco.as$TerrType)
anova(decompk.soil.eco.acesac)

####QUERUB####
decompk.row.soil.eco.qr=decompk.row.soil.eco[decompk.row.soil.eco$Species=="QUERUB",]
#Long model
decompk.soil.long.querub=lme(decompk~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long,random=~1|Plot, data=decompk.row.soil.eco.qr)
anova(decompk.soil.long.querub)

#Short model
decompk.soil.short.querub=lme(decompk~Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short,random=~1|Plot, data=decompk.row.soil.eco.qr)
anova(decompk.soil.short.querub)

#nug model
decompk.soil.nug.querub=lme(decompk~Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=decompk.row.soil.eco.qr)
anova(decompk.soil.nug.querub)

#Check for an ecosystem effect
decompk.soil.eco.querub = lm(decompk.row.soil.eco.qr$decompk ~ decompk.row.soil.eco.qr$TerrType)
anova(decompk.soil.eco.querub)

###CORE###
decompk.row.soil.eco.qr=decompk.row.soil.eco.qr[decompk.row.soil.eco.qr$EP=="Core",]
#Long model
decompk.soil.long.querub=lme(decompk~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long,random=~1|Plot, data=decompk.row.soil.eco.qr)
anova(decompk.soil.long.querub)

#Short model
decompk.soil.short.querub=lme(decompk~Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short,random=~1|Plot, data=decompk.row.soil.eco.qr)
anova(decompk.soil.short.querub)

#nug model
decompk.soil.nug.querub=lme(decompk~Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=decompk.row.soil.eco.qr)
anova(decompk.soil.nug.querub)

#Check for an ecosystem effect
decompk.soil.eco.querub = lm(decompk.row.soil.eco.qr$decompk ~ decompk.row.soil.eco.qr$TerrType)
anova(decompk.soil.eco.querub)
####CAROVA####
decompk.row.soil.eco.co=decompk.row.soil.eco[decompk.row.soil.eco$Species=="CAROVA",]
#Long model
decompk.soil.long.carova=lme(decompk~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long,random=~1|Plot, data=decompk.row.soil.eco.co)
anova(decompk.soil.long.carova)

#Short model
decompk.soil.short.carova=lme(decompk~Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short,random=~1|Plot, data=decompk.row.soil.eco.co)
anova(decompk.soil.short.carova)

#nug model
decompk.soil.nug.carova=lme(decompk~Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=decompk.row.soil.eco.co)
anova(decompk.soil.nug.carova)

#Check for an ecosystem effect
decompk.soil.eco.carova = lm(decompk.row.soil.eco.co$decompk ~ decompk.row.soil.eco.co$TerrType)
anova(decompk.soil.eco.carova)

###CORE###
decompk.row.soil.eco.co=decompk.row.soil.eco.co[decompk.row.soil.eco.co$EP=="Core",]
#Long model
decompk.soil.long.carova=lme(decompk~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long,random=~1|Plot, data=decompk.row.soil.eco.co)
anova(decompk.soil.long.carova)

#Short model
decompk.soil.short.carova=lme(decompk~Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short,random=~1|Plot, data=decompk.row.soil.eco.co)
anova(decompk.soil.short.carova)

#nug model
decompk.soil.nug.carova=lme(decompk~Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=decompk.row.soil.eco.co)
anova(decompk.soil.nug.carova)

#Check for an ecosystem effect
decompk.soil.eco.carova = lm(decompk.row.soil.eco.co$decompk ~ decompk.row.soil.eco.co$TerrType)
anova(decompk.soil.eco.carova)
```

```{r RDA decomp to soil}
decompk.col.soil=merge(decompk.allspec.col,soil.dat,by="Plot")
decompk.col.soil=merge(decompk.col.soil,plotdesig, by="Plot")
dim(decompk.col.soil)
colnames(decompk.col.soil)
decompk.col.soil=decompk.col.soil[,c(1:2,4,6,3,5,7,8:46)]
#Force data as.numeric
decompk.col.soil[,5]=as.numeric(as.character(decompk.col.soil[,5]))
decompk.col.soil[,6]=as.numeric(as.character(decompk.col.soil[,6]))
decompk.col.soil[,7]=as.numeric(as.character(decompk.col.soil[,7]))
decompk.col.soil=na.exclude(decompk.col.soil)
dim(decompk.col.soil)

##ALL soil variables does not have a significant effect (could be from over saturation of model from too many variables?)
## Full model
decompk.rda.fulsoil = rda(decompk.col.soil[,5:7], decompk.col.soil[,17:41])
anova(decompk.rda.fulsoil)
RsquareAdj(decompk.rda.fulsoil)
global.thresh=RsquareAdj(decompk.rda.fulsoil)$adj.r.squared

#long variables
decompk.rda.fulsoil = rda(decompk.col.soil[,5:7], decompk.col.soil[,17:24])
anova(decompk.rda.fulsoil)
RsquareAdj(decompk.rda.fulsoil)
global.thresh=RsquareAdj(decompk.rda.fulsoil)$adj.r.squared

decompk.rda.fulsoil.none = rda(decompk.col.soil[,5:7]~1)
decompk.rda.fulsoil = rda(decompk.col.soil[,5:7], decompk.col.soil[,17:24])

decompk.rda.fulsoil.full=rda(decompk.col.soil[,5:7]~decompk.col.soil$Ptot_long+decompk.col.soil$Po_long+decompk.col.soil$pH_long+decompk.col.soil$moist_long +decompk.col.soil$ps1_long+decompk.col.soil$ps2_long+decompk.col.soil$percc_long+decompk.col.soil$cton_long)

decompk.sel=ordiR2step(decompk.rda.fulsoil.none,scope=formula(decompk.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
decompk.sel
#forward selection: ph_long

#nug variables
decompk.rda.fulsoil = rda(decompk.col.soil[,5:7], decompk.col.soil[,25:33])
anova(decompk.rda.fulsoil)
RsquareAdj(decompk.rda.fulsoil)
global.thresh=RsquareAdj(decompk.rda.fulsoil)$adj.r.squared
###NOT SIGNIFICANT

#short variables
decompk.rda.fulsoil = rda(decompk.col.soil[,5:7], decompk.col.soil[,34:41])
anova(decompk.rda.fulsoil)
RsquareAdj(decompk.rda.fulsoil)
global.thresh=RsquareAdj(decompk.rda.fulsoil)$adj.r.squared
###NOT SIGNIFICANT'

##Check for an ecosystem effect, like we did in the tree manuscript
colnames(decompk.col.soil)
decompk.rda.ecosys = rda(decompk.col.soil[,5:7], as.factor(decompk.col.soil[,42]))
anova(decompk.rda.fulsoil)
RsquareAdj(decompk.rda.fulsoil)
global.thresh=RsquareAdj(decompk.rda.fulsoil)$adj.r.squared

###Core+edge variables
##ALL soil variables does not have a significant effect (could be from over saturation of model from too many variables?)
decompk.col.soil=decompk.col.soil[decompk.col.soil$EP=="Core"|decompk.col.soil$EP=="Edge",]
#long variables
decompk.rda.fulsoil = rda(decompk.col.soil[,5:7], decompk.col.soil[,17:24])
anova(decompk.rda.fulsoil)
RsquareAdj(decompk.rda.fulsoil)
global.thresh=RsquareAdj(decompk.rda.fulsoil)$adj.r.squared

decompk.rda.fulsoil.none = rda(decompk.col.soil[,5:7]~1)
decompk.rda.fulsoil = rda(decompk.col.soil[,5:7], decompk.col.soil[,17:24])

decompk.rda.fulsoil.full=rda(decompk.col.soil[,5:7]~decompk.col.soil$Ptot_long+decompk.col.soil$Po_long+decompk.col.soil$pH_long+decompk.col.soil$moist_long +decompk.col.soil$ps1_long+decompk.col.soil$ps2_long+decompk.col.soil$percc_long+decompk.col.soil$cton_long)

decompk.sel=ordiR2step(decompk.rda.fulsoil.none,scope=formula(decompk.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
decompk.sel
#forward selection: ph_long

#nug variables
decompk.rda.fulsoil = rda(decompk.col.soil[,5:7], decompk.col.soil[,25:33])
anova(decompk.rda.fulsoil)
RsquareAdj(decompk.rda.fulsoil)
global.thresh=RsquareAdj(decompk.rda.fulsoil)$adj.r.squared
###NOT SIGNIFICANT

#short variables
decompk.rda.fulsoil = rda(decompk.col.soil[,5:7], decompk.col.soil[,34:41])
anova(decompk.rda.fulsoil)
RsquareAdj(decompk.rda.fulsoil)
global.thresh=RsquareAdj(decompk.rda.fulsoil)$adj.r.squared
###NOT SIGNIFICANT'

##Check for ecosystem effect like we did in the tree manuscript
colnames(decompk.col.soil)
decompk.rda.ecosys = rda(decompk.col.soil[,5:7], as.factor(decompk.col.soil[,42]))
anova(decompk.rda.fulsoil)
RsquareAdj(decompk.rda.fulsoil)
global.thresh=RsquareAdj(decompk.rda.fulsoil)$adj.r.squared


###Core variables
##ALL soil variables does not have a significant effect (could be from over saturation of model from too many variables?)
decompk.col.soil=decompk.col.soil[decompk.col.soil$EP=="Core",]
#long variables
decompk.rda.fulsoil = rda(decompk.col.soil[,5:7], decompk.col.soil[,17:24])
anova(decompk.rda.fulsoil)
RsquareAdj(decompk.rda.fulsoil)
global.thresh=RsquareAdj(decompk.rda.fulsoil)$adj.r.squared

decompk.rda.fulsoil.none = rda(decompk.col.soil[,5:7]~1)
decompk.rda.fulsoil = rda(decompk.col.soil[,5:7], decompk.col.soil[,17:24])

decompk.rda.fulsoil.full=rda(decompk.col.soil[,5:7]~decompk.col.soil$Ptot_long+decompk.col.soil$Po_long+decompk.col.soil$pH_long+decompk.col.soil$moist_long +decompk.col.soil$ps1_long+decompk.col.soil$ps2_long+decompk.col.soil$percc_long+decompk.col.soil$cton_long)

decompk.sel=ordiR2step(decompk.rda.fulsoil.none,scope=formula(decompk.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
decompk.sel
#forward selection: ph_long

#nug variables
decompk.rda.fulsoil = rda(decompk.col.soil[,5:7], decompk.col.soil[,25:33])
anova(decompk.rda.fulsoil)
RsquareAdj(decompk.rda.fulsoil)
global.thresh=RsquareAdj(decompk.rda.fulsoil)$adj.r.squared
###NOT SIGNIFICANT

#short variables
decompk.rda.fulsoil = rda(decompk.col.soil[,5:7], decompk.col.soil[,34:41])
anova(decompk.rda.fulsoil)
RsquareAdj(decompk.rda.fulsoil)
global.thresh=RsquareAdj(decompk.rda.fulsoil)$adj.r.squared
###NOT SIGNIFICANT'

##Check for an ecosystem effect
colnames(decompk.col.soil)
decompk.rda.ecosys = rda(decompk.col.soil[,5:7], as.factor(decompk.col.soil[,42]))
anova(decompk.rda.fulsoil)
RsquareAdj(decompk.rda.fulsoil)
global.thresh=RsquareAdj(decompk.rda.fulsoil)$adj.r.squared
```
```{r RDA decomp to leaf chem}
## Load the leaf chemistry data
leafchem.avg=read.csv("C:/Users/crc31/OneDrive/Documents/School/Research/Data/Decomp/leaf chemistry averages.csv", header=TRUE)
lig.n=read.csv("costech.data.avg.csv",header=TRUE)

## Merge leaf chem averages to the decay rates.
decayk.chem=merge(decompk.allspec.row,leafchem.avg,by="Species")
dim(decayk.chem)
## Merge in the costech data
decayk.chem=merge(decayk.chem,lig.n,by="Species")

## stats; respsonse variable: decay rate, explanatory variables: leaf chem
#AOV with NPE
NPE.k=aov(decayk.chem$decompk~decayk.chem$Nonpolar.extractives)
anova(NPE.k)
#AOV with PE
PE.k=aov(decayk.chem$decompk~decayk.chem$Polar.extractives)
anova(PE.k)
#AOV with AH
AH.k=aov(decayk.chem$decompk~decayk.chem$AH.compounds)
anova(AH.k)
#AOV with NAH
NAH.k=aov(decayk.chem$decompk~decayk.chem$NAH.compounds)
anova(NAH.k)
##AOV with C:N
cton.k=aov(decayk.chem$decompk~decayk.chem$C.N)
anova(cton.k)
##AOV with nitrogen
n.k=aov(decayk.chem$decompk~decayk.chem$Nitrogen)
anova(n.k)

## Decay by species. I'm sure this is done somwhere else, but I'm too lazy to find it... Here we go.
species.k=aov(decayk.chem$decompk~decayk.chem$Species)
anova(species.k)
```
```{r RDA decomp to enzyme}
##Merge the enzyme activity with the decompk rates
decompk.enzyme.dopa=merge(decompk.allspec.row,dopaact.dat, by="Plot")
decompk.rda.kdopa = rda(as.numeric(as.character(decompk.enzyme.dopa[,c(3,5,7)])), Enzyme, data=decompk.enzyme.dopa)
anova(decompk.rda.kdopa)
RsquareAdj(decompk.rda.fulsoil)
global.thresh=RsquareAdj(decompk.rda.fulsoil)$adj.r.squared


##Hydrolase enzymes
decompk.enzyme.hydro=merge(decompk.allspec.col,hydroact.dat, by="Plot")

#RDA?
decompk.rda.k.hydro=lm(as.numeric(as.character(decompk.enzyme.hydro[,c(3,5,7)])),decompk.enzyme.hydro$Enzyme)
```


```{r enzyme harvest position mixed model}
#####Subset and prep the datasets####
#There are still some "Inf" values that are left over from the activity calculations. We'll just remove those, but since we changed all the raw negatives to 1, there should be no "Na" or "NaN" values present to have to contend with.
hydroact.dat=merge(hydroact.dat, decomp.dat)
dopaact.dat=merge(dopaact.dat, decomp.dat)
colnames(dopaact.dat)
dopaact.dat=na.exclude(dopaact.dat)
dopaact.dat=dopaact.dat[dopaact.dat$activity.lg!="Inf",]
dim(dopaact.dat)
hydroact.dat=na.exclude(hydroact.dat)
hydroact.dat=hydroact.dat[hydroact.dat$activity.lg!="Inf",]
dim(hydroact.dat) #we did a fuck ton of hydrolase enzymes, thus all the rows. Don't freak out about mix-matched data from the merge

#Subset all the enzymes into their own dataframes
phos.dat=hydroact.dat[hydroact.dat$Enzyme=="phos",]
phos.ripup=phos.dat[phos.dat$LumpTrans=="R"|phos.dat$LumpTrans=="RU"|phos.dat$LumpTrans=="U",]
phos.botup=phos.dat[phos.dat$LumpTrans=="B"|phos.dat$LumpTrans=="UB"|phos.dat$LumpTrans=="U",]
phos.ripbot=phos.dat[phos.dat$LumpTrans=="R"|phos.dat$LumpTrans=="RB"|phos.dat$LumpTrans=="B",]
phos.ripbot.acesac=phos.ripbot[phos.ripbot$Species=="ACESAC",]
phos.ripup.acesac=phos.ripup[phos.ripup$Species=="ACESAC",]
phos.botup.acesac=phos.botup[phos.botup$Species=="ACESAC",]
phos.ripbot.carova=phos.ripbot[phos.ripbot$Species=="CAROVA",]
phos.ripup.carova=phos.ripup[phos.ripup$Species=="CAROVA",]
phos.botup.carova=phos.botup[phos.botup$Species=="CAROVA",]
phos.ripbot.querub=phos.ripbot[phos.ripbot$Species=="QUERUB",]
phos.ripup.querub=phos.ripup[phos.ripup$Species=="QUERUB",]
phos.botup.querub=phos.botup[phos.botup$Species=="QUERUB",]


bglu.dat=hydroact.dat[hydroact.dat$Enzyme=="bglu",]
bglu.ripup=bglu.dat[bglu.dat$LumpTrans=="R"|bglu.dat$LumpTrans=="RU"|bglu.dat$LumpTrans=="U",]
bglu.botup=bglu.dat[bglu.dat$LumpTrans=="B"|bglu.dat$LumpTrans=="UB"|bglu.dat$LumpTrans=="U",]
bglu.ripbot=bglu.dat[bglu.dat$LumpTrans=="R"|bglu.dat$LumpTrans=="RB"|bglu.dat$LumpTrans=="B",]
bglu.ripbot.acesac=bglu.ripbot[bglu.ripbot$Species=="ACESAC",]
bglu.ripup.acesac=bglu.ripup[bglu.ripup$Species=="ACESAC",]
bglu.botup.acesac=bglu.botup[bglu.botup$Species=="ACESAC",]
bglu.ripbot.carova=bglu.ripbot[bglu.ripbot$Species=="CAROVA",]
bglu.ripup.carova=bglu.ripup[bglu.ripup$Species=="CAROVA",]
bglu.botup.carova=bglu.botup[bglu.botup$Species=="CAROVA",]
bglu.ripbot.querub=bglu.ripbot[bglu.ripbot$Species=="QUERUB",]
bglu.ripup.querub=bglu.ripup[bglu.ripup$Species=="QUERUB",]
bglu.botup.querub=bglu.botup[bglu.botup$Species=="QUERUB",]

bcell.dat=hydroact.dat[hydroact.dat$Enzyme=="bcell",]
bcell.ripup=bcell.dat[bcell.dat$LumpTrans=="R"|bcell.dat$LumpTrans=="RU"|bcell.dat$LumpTrans=="U",]
bcell.botup=bcell.dat[bcell.dat$LumpTrans=="B"|bcell.dat$LumpTrans=="UB"|bcell.dat$LumpTrans=="U",]
bcell.ripbot=bcell.dat[bcell.dat$LumpTrans=="R"|bcell.dat$LumpTrans=="RB"|bcell.dat$LumpTrans=="B",]
bcell.ripbot.acesac=bcell.ripbot[bcell.ripbot$Species=="ACESAC",]
bcell.ripup.acesac=bcell.ripup[bcell.ripup$Species=="ACESAC",]
bcell.botup.acesac=bcell.botup[bcell.botup$Species=="ACESAC",]
bcell.ripbot.carova=bcell.ripbot[bcell.ripbot$Species=="CAROVA",]
bcell.ripup.carova=bcell.ripup[bcell.ripup$Species=="CAROVA",]
bcell.botup.carova=bcell.botup[bcell.botup$Species=="CAROVA",]
bcell.ripbot.querub=bcell.ripbot[bcell.ripbot$Species=="QUERUB",]
bcell.ripup.querub=bcell.ripup[bcell.ripup$Species=="QUERUB",]
bcell.botup.querub=bcell.botup[bcell.botup$Species=="QUERUB",]

bxyl.dat=hydroact.dat[hydroact.dat$Enzyme=="bxyl",]
bxyl.ripup=bxyl.dat[bxyl.dat$LumpTrans=="R"|bxyl.dat$LumpTrans=="RU"|bxyl.dat$LumpTrans=="U",]
bxyl.botup=bxyl.dat[bxyl.dat$LumpTrans=="B"|bxyl.dat$LumpTrans=="UB"|bxyl.dat$LumpTrans=="U",]
bxyl.ripbot=bxyl.dat[bxyl.dat$LumpTrans=="R"|bxyl.dat$LumpTrans=="RB"|bxyl.dat$LumpTrans=="B",]
bxyl.ripbot.acesac=bxyl.ripbot[bxyl.ripbot$Species=="ACESAC",]
bxyl.ripup.acesac=bxyl.ripup[bxyl.ripup$Species=="ACESAC",]
bxyl.botup.acesac=bxyl.botup[bxyl.botup$Species=="ACESAC",]
bxyl.ripbot.carova=bxyl.ripbot[bxyl.ripbot$Species=="CAROVA",]
bxyl.ripup.carova=bxyl.ripup[bxyl.ripup$Species=="CAROVA",]
bxyl.botup.carova=bxyl.botup[bxyl.botup$Species=="CAROVA",]
bxyl.ripbot.querub=bxyl.ripbot[bxyl.ripbot$Species=="QUERUB",]
bxyl.ripup.querub=bxyl.ripup[bxyl.ripup$Species=="QUERUB",]
bxyl.botup.querub=bxyl.botup[bxyl.botup$Species=="QUERUB",]

nag.dat=hydroact.dat[hydroact.dat$Enzyme=="nag",]
nag.ripup=nag.dat[nag.dat$LumpTrans=="R"|nag.dat$LumpTrans=="RU"|nag.dat$LumpTrans=="U",]
nag.botup=nag.dat[nag.dat$LumpTrans=="B"|nag.dat$LumpTrans=="UB"|nag.dat$LumpTrans=="U",]
nag.ripbot=nag.dat[nag.dat$LumpTrans=="R"|nag.dat$LumpTrans=="RB"|nag.dat$LumpTrans=="B",]
nag.ripbot.acesac=nag.ripbot[nag.ripbot$Species=="ACESAC",]
nag.ripup.acesac=nag.ripup[nag.ripup$Species=="ACESAC",]
nag.botup.acesac=nag.botup[nag.botup$Species=="ACESAC",]
nag.ripbot.carova=nag.ripbot[nag.ripbot$Species=="CAROVA",]
nag.ripup.carova=nag.ripup[nag.ripup$Species=="CAROVA",]
nag.botup.carova=nag.botup[nag.botup$Species=="CAROVA",]
nag.ripbot.querub=nag.ripbot[nag.ripbot$Species=="QUERUB",]
nag.ripup.querub=nag.ripup[nag.ripup$Species=="QUERUB",]
nag.botup.querub=nag.botup[nag.botup$Species=="QUERUB",]

lap.dat=hydroact.dat[hydroact.dat$Enzyme=="lap",]
lap.ripup=lap.dat[lap.dat$LumpTrans=="R"|lap.dat$LumpTrans=="RU"|lap.dat$LumpTrans=="U",]
lap.botup=lap.dat[lap.dat$LumpTrans=="B"|lap.dat$LumpTrans=="UB"|lap.dat$LumpTrans=="U",]
lap.ripbot=lap.dat[lap.dat$LumpTrans=="R"|lap.dat$LumpTrans=="RB"|lap.dat$LumpTrans=="B",]
lap.ripbot.acesac=lap.ripbot[lap.ripbot$Species=="ACESAC",]
lap.ripup.acesac=lap.ripup[lap.ripup$Species=="ACESAC",]
lap.botup.acesac=lap.botup[lap.botup$Species=="ACESAC",]
lap.ripbot.carova=lap.ripbot[lap.ripbot$Species=="CAROVA",]
lap.ripup.carova=lap.ripup[lap.ripup$Species=="CAROVA",]
lap.botup.carova=lap.botup[lap.botup$Species=="CAROVA",]
lap.ripbot.querub=lap.ripbot[lap.ripbot$Species=="QUERUB",]
lap.ripup.querub=lap.ripup[lap.ripup$Species=="QUERUB",]
lap.botup.querub=lap.botup[lap.botup$Species=="QUERUB",]

dopa.dat=dopaact.dat[dopaact.dat$Enzyme=="dopa",]
dopa.ripup=dopa.dat[dopa.dat$LumpTrans=="R"|dopa.dat$LumpTrans=="RU"|dopa.dat$LumpTrans=="U",]
dopa.botup=dopa.dat[dopa.dat$LumpTrans=="B"|dopa.dat$LumpTrans=="UB"|dopa.dat$LumpTrans=="U",]
dopa.ripbot=dopa.dat[dopa.dat$LumpTrans=="R"|dopa.dat$LumpTrans=="RB"|dopa.dat$LumpTrans=="B",]
dopa.ripbot.acesac=dopa.ripbot[dopa.ripbot$Species=="ACESAC",]
dopa.ripup.acesac=dopa.ripup[dopa.ripup$Species=="ACESAC",]
dopa.botup.acesac=dopa.botup[dopa.botup$Species=="ACESAC",]
dopa.ripbot.carova=dopa.ripbot[dopa.ripbot$Species=="CAROVA",]
dopa.ripup.carova=dopa.ripup[dopa.ripup$Species=="CAROVA",]
dopa.botup.carova=dopa.botup[dopa.botup$Species=="CAROVA",]
dopa.ripbot.querub=dopa.ripbot[dopa.ripbot$Species=="QUERUB",]
dopa.ripup.querub=dopa.ripup[dopa.ripup$Species=="QUERUB",]
dopa.botup.querub=dopa.botup[dopa.botup$Species=="QUERUB",]

h2o2.dat=dopaact.dat[dopaact.dat$Enzyme=="h2o2",]
h2o2.ripup=h2o2.dat[h2o2.dat$LumpTrans=="R"|h2o2.dat$LumpTrans=="RU"|h2o2.dat$LumpTrans=="U",]
h2o2.botup=h2o2.dat[h2o2.dat$LumpTrans=="B"|h2o2.dat$LumpTrans=="UB"|h2o2.dat$LumpTrans=="U",]
h2o2.ripbot=h2o2.dat[h2o2.dat$LumpTrans=="R"|h2o2.dat$LumpTrans=="RB"|h2o2.dat$LumpTrans=="B",]
h2o2.ripbot.acesac=h2o2.ripbot[h2o2.ripbot$Species=="ACESAC",]
h2o2.ripup.acesac=h2o2.ripup[h2o2.ripup$Species=="ACESAC",]
h2o2.botup.acesac=h2o2.botup[h2o2.botup$Species=="ACESAC",]
h2o2.ripbot.carova=h2o2.ripbot[h2o2.ripbot$Species=="CAROVA",]
h2o2.ripup.carova=h2o2.ripup[h2o2.ripup$Species=="CAROVA",]
h2o2.botup.carova=h2o2.botup[h2o2.botup$Species=="CAROVA",]
h2o2.ripbot.querub=h2o2.ripbot[h2o2.ripbot$Species=="QUERUB",]
h2o2.ripup.querub=h2o2.ripup[h2o2.ripup$Species=="QUERUB",]
h2o2.botup.querub=h2o2.botup[h2o2.botup$Species=="QUERUB",]

####Full data models. Literally useless.####
#Lme using log activity as repsonse variable 
dopamod=lme(activity.lg~Enzyme,random=~1|Plot, data=dopaact.dat)
anova(dopamod) #No significance

hydromod=lme(activity.lg~Enzyme*TerrType,random=~1|Plot, data=hydroact.dat)
anova(hydromod) #Significance in enzyme type
hydromod=lme(activity.lg~Enzyme*Ecotone,random=~1|Plot, data=hydroact.dat)
anova(hydromod) #No significance
hydromod=lme(activity.lg~Enzyme,random=~1|Plot, data=hydroact.dat)
anova(hydromod)
summary(hydromod) #Each enzyme is significantly different. I don't know that that is much of an interesting result in and of itself. If they weren't going to be different, they'd be the same damn enzyme.
hydromod=lme(activity.lg~LumpTrans*Species,random=~1|Plot, data=hydroact.dat)
anova(hydromod)

####phos stats####
##Riparian Upland
phos.ripup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=phos.ripup)
anova(phos.ripup.mod)
emmeans(phos.ripup.mod,pairwise~Species)

#order
phos.ripup$LumpTrans=factor(phos.ripup$LumpTrans, levels=c("R","RU","U"))
phos.ripup$Species=factor(phos.ripup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(phos.ripup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")

phos.ripup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=phos.ripup.acesac)
anova(phos.ripup.acesac.mod)
emmeans(phos.ripup.acesac.mod, pairwise~Harvest)

phos.ripup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=phos.ripup.carova)
anova(phos.ripup.carova.mod)
emmeans(phos.ripup.carova.mod, pairwise~Harvest)

phos.ripup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=phos.ripup.querub)
anova(phos.ripup.querub.mod)
emmeans(phos.ripup.querub.mod, pairwise~Harvest)

##Bottomland Upland
phos.botup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=phos.botup)
phos.botup.mod=lme(activity.lg~Species*Harvest, random=~1|Plot, data=phos.botup)
anova(phos.botup.mod)
emmeans(phos.botup.mod,pairwise~Species)

#order
phos.botup$LumpTrans=factor(phos.botup$LumpTrans, levels=c("B","UB","U"))
phos.botup$Species=factor(phos.botup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(phos.botup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))

#plot
ggplot(phos.botup, aes(x=Species,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Bottomland-Uopland Transect")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.position="none")+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(4,10))

phos.botup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=phos.botup.acesac)
anova(phos.botup.acesac.mod)
emmeans(phos.botup.acesac.mod, pairwise~Harvest)

phos.botup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=phos.botup.carova)
anova(phos.botup.carova.mod)
#This doesn't run together, but  neither is significant alone, so it doesn't matter.

phos.botup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=phos.botup.querub)
anova(phos.botup.querub.mod)
#emmeans(phos.botup.querub.mod, pairwise~Harvest)

##Riparian Bottomland
#phos.ripbot.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=phos.ripbot)
phos.ripbot.mod=lme(activity.lg~Species*Harvest, random=~1|Plot, data=phos.ripbot)
anova(phos.ripbot.mod)
emmeans(phos.ripbot.mod,pairwise~Species)

#order
phos.ripbot$LumpTrans=factor(phos.ripbot$LumpTrans, levels=c("R","RB","B"))
phos.ripbot$Species=factor(phos.ripbot$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(phos.ripbot, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")

#plot
ggplot(phos.ripbot, aes(x=Species,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.position = "none")+
  ylab("Enzyme activity (nmol/h/g)")

phos.ripbot.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=phos.ripbot.acesac)
anova(phos.ripbot.acesac.mod)
emmeans(phos.ripbot.acesac.mod, pairwise~Harvest)

phos.ripbot.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=phos.ripbot.carova)
anova(phos.ripbot.carova.mod)
emmeans(phos.ripbot.carova.mod, pairwise~Harvest)
##This also doesn't run with both variables in the model, but runs individually? Harvest is significant on it's own.

phos.ripbot.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=phos.ripbot.querub)
anova(phos.ripbot.querub.mod)
#emmeans(phos.ripbot.querub.mod, pairwise~Harvest)


####bglu stats####
##Riparian Upland
bglu.ripup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=bglu.ripup)
anova(bglu.ripup.mod)
emmeans(bglu.ripup.mod,pairwise~Species*Harvest)

#order
bglu.ripup$LumpTrans=factor(bglu.ripup$LumpTrans, levels=c("R","RU","U"))
bglu.ripup$Species=factor(bglu.ripup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(bglu.ripup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")

bglu.ripup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bglu.ripup.acesac)
anova(bglu.ripup.acesac.mod)
emmeans(bglu.ripup.acesac.mod, pairwise~Harvest)

bglu.ripup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bglu.ripup.carova)
anova(bglu.ripup.carova.mod)
emmeans(bglu.ripup.carova.mod, pairwise~Harvest)

bglu.ripup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bglu.ripup.querub)
anova(bglu.ripup.querub.mod)
#emmeans(bglu.ripup.querub.mod, pairwise~Harvest)

##Bottomland Upland
bglu.botup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=bglu.botup)
anova(bglu.botup.mod)

#order
bglu.botup$LumpTrans=factor(bglu.botup$LumpTrans, levels=c("B","UB","U"))
bglu.botup$Species=factor(bglu.botup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(bglu.botup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))

bglu.botup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bglu.botup.acesac)
anova(bglu.botup.acesac.mod)
emmeans(bglu.botup.acesac.mod, pairwise~Harvest)

bglu.botup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bglu.botup.carova)
anova(bglu.botup.carova.mod)
#emmeans(bglu.botup.carova.mod, pairwise~Harvest)
#No significance with either of these on their own.

bglu.botup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bglu.botup.querub)
anova(bglu.botup.querub.mod)
emmeans(bglu.botup.querub.mod, pairwise~Harvest)

##Riparian Bottomland
bglu.ripbot.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=bglu.ripbot)
anova(bglu.ripbot.mod)

#order
bglu.ripbot$LumpTrans=factor(bglu.ripbot$LumpTrans, levels=c("R","RB","B"))
bglu.ripbot$Species=factor(bglu.ripbot$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(bglu.ripbot, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")

bglu.ripbot.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bglu.ripbot.acesac)
anova(bglu.ripbot.acesac.mod)
emmeans(bglu.ripbot.acesac.mod, pairwise~Harvest)

bglu.ripbot.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bglu.ripbot.carova)
anova(bglu.ripbot.carova.mod)
emmeans(bglu.ripbot.carova.mod, pairwise~Harvest)
#Only H1-H3 on their own.

bglu.ripbot.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bglu.ripbot.querub)
anova(bglu.ripbot.querub.mod)
#emmeans(bglu.ripbot.querub.mod, pairwise~Harvest)


####bcell stats####
##Riparian Upland
bcell.ripup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=bcell.ripup)
anova(bcell.ripup.mod)
emmeans(bcell.ripup.mod,pairwise~Species)

#order
bcell.ripup$LumpTrans=factor(bcell.ripup$LumpTrans, levels=c("R","RU","U"))
bcell.ripup$Species=factor(bcell.ripup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(bcell.ripup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")

bcell.ripup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bcell.ripup.acesac)
anova(bcell.ripup.acesac.mod)
emmeans(bcell.ripup.acesac.mod, pairwise~Harvest)

bcell.ripup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bcell.ripup.carova)
anova(bcell.ripup.carova.mod)
emmeans(bcell.ripup.carova.mod, pairwise~Harvest)

bcell.ripup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bcell.ripup.querub)
anova(bcell.ripup.querub.mod)
emmeans(bcell.ripup.querub.mod, pairwise~Harvest)

##Bottomland Upland
bcell.botup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=bcell.botup)
anova(bcell.botup.mod)

#order
bcell.botup$LumpTrans=factor(bcell.botup$LumpTrans, levels=c("B","UB","U"))
bcell.botup$Species=factor(bcell.botup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(bcell.botup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))

bcell.botup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bcell.botup.acesac)
anova(bcell.botup.acesac.mod)
emmeans(bcell.botup.acesac.mod, pairwise~Harvest)

bcell.botup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bcell.botup.carova)
anova(bcell.botup.carova.mod)
#emmeans(bcell.botup.carova.mod, pairwise~Harvest)
##nothing is significant on its own.

bcell.botup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bcell.botup.querub)
anova(bcell.botup.querub.mod)
#emmeans(bcell.botup.querub.mod, pairwise~Harvest)

##Riparian Bottomland
bcell.ripbot.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=bcell.ripbot)
anova(bcell.ripbot.mod)
emmeans(bcell.ripbot.mod,pairwise~Species)

#order
bcell.ripbot$LumpTrans=factor(bcell.ripbot$LumpTrans, levels=c("R","RB","B"))
bcell.ripbot$Species=factor(bcell.ripbot$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(bcell.ripbot, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")

bcell.ripbot.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bcell.ripbot.acesac)
anova(bcell.ripbot.acesac.mod)
emmeans(bcell.ripbot.acesac.mod, pairwise~Harvest)

bcell.ripbot.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bcell.ripbot.carova)
anova(bcell.ripbot.carova.mod)
emmeans(bcell.ripbot.carova.mod, pairwise~Harvest)

bcell.ripbot.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bcell.ripbot.querub)
anova(bcell.ripbot.querub.mod)
emmeans(bcell.ripbot.querub.mod, pairwise~Harvest)

####bxyl stats####
bxyl.ripup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=bxyl.ripup)
anova(bxyl.ripup.mod)
emmeans(bxyl.ripup.mod,pairwise~Species)

#order
bxyl.ripup$LumpTrans=factor(bxyl.ripup$LumpTrans, levels=c("R","RU","U"))
bxyl.ripup$Species=factor(bxyl.ripup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(bxyl.ripup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")

bxyl.ripup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bxyl.ripup.acesac)
anova(bxyl.ripup.acesac.mod)
emmeans(bxyl.ripup.acesac.mod, pairwise~Harvest)

bxyl.ripup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bxyl.ripup.carova)
anova(bxyl.ripup.carova.mod)
emmeans(bxyl.ripup.carova.mod, pairwise~Harvest)

bxyl.ripup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bxyl.ripup.querub)
anova(bxyl.ripup.querub.mod)
emmeans(bxyl.ripup.querub.mod, pairwise~Harvest)

##Bottomland Upland
bxyl.botup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=bxyl.botup)
anova(bxyl.botup.mod)

#order
bxyl.botup$LumpTrans=factor(bxyl.botup$LumpTrans, levels=c("B","UB","U"))
bxyl.botup$Species=factor(bxyl.botup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(bxyl.botup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))

bxyl.botup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bxyl.botup.acesac)
anova(bxyl.botup.acesac.mod)
emmeans(bxyl.botup.acesac.mod, pairwise~Harvest)

bxyl.botup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bxyl.botup.carova)
anova(bxyl.botup.carova.mod)
#emmeans(bxyl.botup.carova.mod, pairwise~Harvest)

bxyl.botup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bxyl.botup.querub)
anova(bxyl.botup.querub.mod)
emmeans(bxyl.botup.querub.mod, pairwise~Harvest)

##Riparian Bottomland
bxyl.ripbot.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=bxyl.ripbot)
anova(bxyl.ripbot.mod)
emmeans(bxyl.ripbot.mod,pairwise~Species)

#order
bxyl.ripbot$LumpTrans=factor(bxyl.ripbot$LumpTrans, levels=c("R","RB","B"))
bxyl.ripbot$Species=factor(bxyl.ripbot$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(bxyl.ripbot, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")

bxyl.ripbot.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bxyl.ripbot.acesac)
anova(bxyl.ripbot.acesac.mod)
emmeans(bxyl.ripbot.acesac.mod, pairwise~Harvest)

bxyl.ripbot.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bxyl.ripbot.carova)
anova(bxyl.ripbot.carova.mod)
emmeans(bxyl.ripbot.carova.mod, pairwise~Harvest)

bxyl.ripbot.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=bxyl.ripbot.querub)
anova(bxyl.ripbot.querub.mod)
emmeans(bxyl.ripbot.querub.mod, pairwise~Harvest)

####lap stats####
##Riparian Upland
lap.ripup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=lap.ripup)
anova(lap.ripup.mod)

#order
lap.ripup$LumpTrans=factor(lap.ripup$LumpTrans, levels=c("R","RU","U"))
lap.ripup$Species=factor(lap.ripup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(lap.ripup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")

lap.ripup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=lap.ripup.acesac)
anova(lap.ripup.acesac.mod)
#emmeans(lap.ripup.acesac.mod, pairwise~Harvest)

lap.ripup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=lap.ripup.carova)
anova(lap.ripup.carova.mod)
emmeans(lap.ripup.carova.mod, pairwise~Harvest)

lap.ripup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=lap.ripup.querub)
anova(lap.ripup.querub.mod) #Marginal
#emmeans(lap.ripup.querub.mod, pairwise~Harvest)

##Bottomland Upland
lap.botup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=lap.botup)
anova(lap.botup.mod)

#order
lap.botup$LumpTrans=factor(lap.botup$LumpTrans, levels=c("B","UB","U"))
lap.botup$Species=factor(lap.botup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(lap.botup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))

lap.botup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=lap.botup.acesac)
anova(lap.botup.acesac.mod)
#emmeans(lap.botup.acesac.mod, pairwise~Harvest)

lap.botup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=lap.botup.carova)
anova(lap.botup.carova.mod)
#emmeans(lap.botup.carova.mod, pairwise~Harvest)

lap.botup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=lap.botup.querub)
anova(lap.botup.querub.mod) 
#emmeans(lap.botup.querub.mod, pairwise~Harvest)

#Riparian Bottomland
lap.ripbot.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=lap.ripbot)
anova(lap.ripbot.mod)

#order
lap.ripbot$LumpTrans=factor(lap.ripbot$LumpTrans, levels=c("R","RB","B"))
lap.ripbot$Species=factor(lap.ripbot$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(lap.ripbot, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")

lap.ripbot.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=lap.ripbot.acesac)
anova(lap.ripbot.acesac.mod)
emmeans(lap.ripbot.acesac.mod, pairwise~Harvest)

lap.ripbot.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=lap.ripbot.carova)
anova(lap.ripbot.carova.mod)
#emmeans(lap.ripbot.carova.mod, pairwise~Harvest)

lap.ripbot.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=lap.ripbot.querub)
anova(lap.ripbot.querub.mod) #Marginal
#emmeans(lap.ripbot.querub.mod, pairwise~Harvest)

####nag stats####
##Riparian Upland
nag.ripup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=nag.ripup)
anova(nag.ripup.mod)
emmeans(nag.ripup.mod,pairwise~Species)

#order
nag.ripup$LumpTrans=factor(nag.ripup$LumpTrans, levels=c("R","RU","U"))
nag.ripup$Species=factor(nag.ripup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(nag.ripup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")

nag.ripup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=nag.ripup.acesac)
anova(nag.ripup.acesac.mod)
emmeans(nag.ripup.acesac.mod, pairwise~Harvest)

nag.ripup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=nag.ripup.carova)
anova(nag.ripup.carova.mod)
emmeans(nag.ripup.carova.mod, pairwise~Harvest)

nag.ripup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=nag.ripup.querub)
anova(nag.ripup.querub.mod)
emmeans(nag.ripup.querub.mod, pairwise~Harvest)

#Bottomland Upland
nag.botup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=nag.botup)
anova(nag.botup.mod)

#order
nag.botup$LumpTrans=factor(nag.botup$LumpTrans, levels=c("B","UB","U"))
nag.botup$Species=factor(nag.botup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(nag.botup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))

nag.botup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=nag.botup.acesac)
anova(nag.botup.acesac.mod)
emmeans(nag.botup.acesac.mod, pairwise~Harvest)
#emmeans(nag.botup.acesac.mod, pairwise~LumpTrans)

nag.botup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=nag.botup.carova)
anova(nag.botup.carova.mod)
#emmeans(nag.botup.carova.mod, pairwise~Harvest)

nag.botup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=nag.botup.querub)
anova(nag.botup.querub.mod)
emmeans(nag.botup.querub.mod, pairwise~Harvest)

##Riparian Bottomland
nag.ripbot.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=nag.ripbot)
anova(nag.ripbot.mod)

#order
nag.ripbot$LumpTrans=factor(nag.ripbot$LumpTrans, levels=c("R","RB","B"))
nag.ripbot$Species=factor(nag.ripbot$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(nag.ripbot, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")

nag.ripbot.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=nag.ripbot.acesac)
anova(nag.ripbot.acesac.mod)
#emmeans(nag.ripbot.acesac.mod, pairwise~Harvest)

nag.ripbot.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=nag.ripbot.carova)
anova(nag.ripbot.carova.mod)
#emmeans(nag.ripbot.carova.mod, pairwise~Harvest)

nag.ripbot.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=nag.ripbot.querub)
anova(nag.ripbot.querub.mod)
#emmeans(nag.ripbot.querub.mod, pairwise~Harvest)

####Dopa stats####
##Riparian Upland
dopa.ripup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=dopa.ripup)
anova(dopa.ripup.mod)

#order
dopa.ripup$LumpTrans=factor(dopa.ripup$LumpTrans, levels=c("R","RU","U"))
dopa.ripup$Species=factor(dopa.ripup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(dopa.ripup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")

dopa.ripup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=dopa.ripup.acesac)
anova(dopa.ripup.acesac.mod)
emmeans(dopa.ripup.acesac.mod, pairwise~Harvest)

dopa.ripup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=dopa.ripup.carova)
anova(dopa.ripup.carova.mod)
#emmeans(dopa.ripup.carova.mod, pairwise~Harvest)

dopa.ripup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=dopa.ripup.querub)
anova(dopa.ripup.querub.mod)
#emmeans(dopa.ripup.querub.mod, pairwise~Harvest)

##Bottomland Upland
dopa.botup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=dopa.botup)
anova(dopa.botup.mod)

#order
dopa.botup$LumpTrans=factor(dopa.botup$LumpTrans, levels=c("B","UB","U"))
dopa.botup$Species=factor(dopa.botup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(dopa.botup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))

dopa.botup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=dopa.botup.acesac)
anova(dopa.botup.acesac.mod)
#emmeans(dopa.botup.acesac.mod, pairwise~Harvest)

dopa.botup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=dopa.botup.carova)
anova(dopa.botup.carova.mod)
#emmeans(dopa.botup.carova.mod, pairwise~Harvest)

dopa.botup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=dopa.botup.querub)
anova(dopa.botup.querub.mod)
#emmeans(dopa.botup.querub.mod, pairwise~Harvest)

##Riparian Bottomland
dopa.ripbot.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=dopa.ripbot)
anova(dopa.ripbot.mod)

#order
dopa.ripbot$LumpTrans=factor(dopa.ripbot$LumpTrans, levels=c("R","RB","B"))
dopa.ripbot$Species=factor(dopa.ripbot$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(dopa.ripbot, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")

dopa.ripbot.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=dopa.ripbot.acesac)
anova(dopa.ripbot.acesac.mod)
emmeans(dopa.ripbot.acesac.mod, pairwise~Harvest)

dopa.ripbot.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=dopa.ripbot.carova)
anova(dopa.ripbot.carova.mod)
#emmeans(dopa.ripbot.carova.mod, pairwise~Harvest)

dopa.ripbot.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=dopa.ripbot.querub)
anova(dopa.ripbot.querub.mod)
#emmeans(dopa.ripbot.querub.mod, pairwise~Harvest)

####h2o2 stats####
##Riparian Upland
h2o2.ripup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=h2o2.ripup)
anova(h2o2.ripup.mod)
emmeans(h2o2.ripup.mod, pairwise~LumpTrans)

#order
h2o2.ripup$LumpTrans=factor(h2o2.ripup$LumpTrans, levels=c("R","RU","U"))
h2o2.ripup$Species=factor(h2o2.ripup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(h2o2.ripup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(-0,10))

h2o2.ripup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=h2o2.ripup.acesac)
anova(h2o2.ripup.acesac.mod)
emmeans(h2o2.ripup.acesac.mod, pairwise~LumpTrans)

h2o2.ripup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=h2o2.ripup.carova)
anova(h2o2.ripup.carova.mod)
emmeans(h2o2.ripup.carova.mod, pairwise~LumpTrans)

h2o2.ripup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=h2o2.ripup.querub)
anova(h2o2.ripup.querub.mod)
emmeans(h2o2.ripup.querub.mod, pairwise~Harvest)
emmeans(h2o2.ripup.querub.mod,pairwise~LumpTrans)

##Bottomland-upland
h2o2.botup.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=h2o2.botup)
anova(h2o2.botup.mod)

#order
h2o2.botup$LumpTrans=factor(h2o2.botup$LumpTrans, levels=c("B","UB","U"))
h2o2.botup$Species=factor(h2o2.botup$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(h2o2.botup, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))

h2o2.botup.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=h2o2.botup.acesac)
anova(h2o2.botup.acesac.mod)
#emmeans(h2o2.botup.acesac.mod, pairwise~LumpTrans)

h2o2.botup.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=h2o2.botup.carova)
anova(h2o2.botup.carova.mod)
#emmeans(h2o2.botup.carova.mod, pairwise~LumpTrans)

h2o2.botup.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=h2o2.botup.querub)
anova(h2o2.botup.querub.mod)
#emmeans(h2o2.botup.querub.mod, pairwise~Harvest)

#riparian bottomland
h2o2.ripbot.mod=lme(activity.lg~LumpTrans*Species, random=~1|Plot, data=h2o2.ripbot)
anova(h2o2.ripbot.mod)
emmeans(h2o2.ripbot.mod, pairwise~LumpTrans)

#order
h2o2.ripbot$LumpTrans=factor(h2o2.ripbot$LumpTrans, levels=c("R","RB","B"))
h2o2.ripbot$Species=factor(h2o2.ripbot$Species, levels=c("CAROVA","ACESAC","QUERUB"))
#plot
ggplot(h2o2.ripbot, aes(x=LumpTrans,y=activity.lg,colour=Species))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(-5,5))

h2o2.ripbot.acesac.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=h2o2.ripbot.acesac)
anova(h2o2.ripbot.acesac.mod)
emmeans(h2o2.ripbot.acesac.mod, pairwise~LumpTrans)

h2o2.ripbot.carova.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=h2o2.ripbot.carova)
anova(h2o2.ripbot.carova.mod)
#emmeans(h2o2.ripbot.carova.mod, pairwise~LumpTrans)

h2o2.ripbot.querub.mod=lme(activity.lg~LumpTrans*Harvest, random=~1|Plot, data=h2o2.ripbot.querub)
anova(h2o2.ripbot.querub.mod)
#emmeans(h2o2.ripbot.querub.mod, pairwise~Harvest)

####phos graph####
##Riparian Upland
#acesac
ggplot(phos.ripup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#carova
ggplot(phos.ripup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#querub
ggplot(phos.ripup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))

##Bottomland Upland
#acesac
phos.botup.acesac$LumpTrans=factor(phos.botup.acesac$LumpTrans, levels=c("B","UB","U"))
ggplot(phos.botup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#carova
phos.botup.carova$LumpTrans=factor(phos.botup.carova$LumpTrans, levels=c("B","UB","U"))
ggplot(phos.botup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#querub
phos.botup.querub$LumpTrans=factor(phos.botup.querub$LumpTrans, levels=c("B","UB","U"))
ggplot(phos.botup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
##Riparian Bottomland
#acesac
phos.ripbot.acesac$LumpTrans=factor(phos.ripbot.acesac$LumpTrans, levels=c("R","RB","B"))
ggplot(phos.ripbot.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#carova
phos.ripbot.carova$LumpTrans=factor(phos.ripbot.carova$LumpTrans, levels=c("R","RB","B"))
ggplot(phos.ripbot.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#querub
phos.ripbot.querub$LumpTrans=factor(phos.ripbot.querub$LumpTrans, levels=c("R","RB","B"))
ggplot(phos.ripbot.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
####bglu graph####
##Riparian Upland
#acesac
ggplot(bglu.ripup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
#carova
ggplot(bglu.ripup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
#querub
ggplot(bglu.ripup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))

##Bottomland Upland
#acesac
bglu.botup.acesac$LumpTrans=factor(bglu.botup.acesac$LumpTrans, levels=c("B","UB","U"))
ggplot(bglu.botup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
#carova
bglu.botup.carova$LumpTrans=factor(bglu.botup.carova$LumpTrans, levels=c("B","UB","U"))
ggplot(bglu.botup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
#querub
bglu.botup.querub$LumpTrans=factor(bglu.botup.querub$LumpTrans, levels=c("B","UB","U"))
ggplot(bglu.botup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
##Riparian Bottomland
#acesac
bglu.ripbot.acesac$LumpTrans=factor(bglu.ripbot.acesac$LumpTrans, levels=c("R","RB","B"))
ggplot(bglu.ripbot.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
#carova
bglu.ripbot.carova$LumpTrans=factor(bglu.ripbotcarova$LumpTrans, levels=c("R","RB","B"))
ggplot(bglu.ripbot.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
#querub
bglu.ripbot.querub$LumpTrans=factor(bglu.ripbot.querub$LumpTrans, levels=c("R","RB","B"))
ggplot(bglu.ripbot.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))

####bcell graph####
##Riparian Upland
#acesac
ggplot(bcell.ripup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#carova
ggplot(bcell.ripup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#querub
ggplot(bcell.ripup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))

##Bottomland Upland
#acesac
bcell.botup.acesac$LumpTrans=factor(bcell.botup.acesac$LumpTrans, levels=c("B","UB","U"))
ggplot(bcell.botup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#carova
bcell.botup.carova$LumpTrans=factor(bcell.botup.carova$LumpTrans, levels=c("B","UB","U"))
ggplot(bcell.botup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#querub
bcell.botup.querub$LumpTrans=factor(bcell.botup.querub$LumpTrans, levels=c("B","UB","U"))
ggplot(bcell.botup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
##Riparian Bottomland
#acesac
bcell.ripbot.acesac$LumpTrans=factor(bcell.ripbot.acesac$LumpTrans, levels=c("R","RB","B"))
ggplot(bcell.ripbot.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#carova
bcell.ripbot.carova$LumpTrans=factor(bcell.ripbot.carova$LumpTrans, levels=c("R","RB","B"))
ggplot(bcell.ripbot.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#querub
bcell.ripbot.querub$LumpTrans=factor(bcell.ripbot.querub$LumpTrans, levels=c("R","RB","B"))
ggplot(bcell.ripbot.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))

####bxyl graph####
##Riparian Upland
#acesac
ggplot(bxyl.ripup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#carova
ggplot(bxyl.ripup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#querub
ggplot(bxyl.ripup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))

##Bottomland Upland
#acesac
bxyl.botup.acesac$LumpTrans=factor(bxyl.botup.acesac$LumpTrans, levels=c("B","UB","U"))
ggplot(bxyl.botup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#carova
bxyl.botup.carova$LumpTrans=factor(bxyl.botup.carova$LumpTrans, levels=c("B","UB","U"))
ggplot(bxyl.botup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#querub
bxyl.botup.querub$LumpTrans=factor(bxyl.botup.querub$LumpTrans, levels=c("B","UB","U"))
ggplot(bxyl.botup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
##Riparian Bottomland
#acesac
bxyl.ripbot.acesac$LumpTrans=factor(bxyl.ripbot.acesac$LumpTrans, levels=c("R","RB","B"))
ggplot(bxyl.ripbot.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#carova
bxyl.ripbot.carova$LumpTrans=factor(bxyl.ripbot.carova$LumpTrans, levels=c("R","RB","B"))
ggplot(bxyl.ripbot.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
#querub
bxyl.ripbot.querub$LumpTrans=factor(bxyl.ripbot.querub$LumpTrans, levels=c("R","RB","B"))
ggplot(bxyl.ripbot.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,10))
####lap graph####
##Riparian Upland
#acesac
ggplot(lap.ripup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,6))
#carova
ggplot(lap.ripup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,6))
#querub
ggplot(lap.ripup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,6))

##Bottomland Upland
#acesac
lap.botup.acesac$LumpTrans=factor(lap.botup.acesac$LumpTrans, levels=c("B","UB","U"))
ggplot(lap.botup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,6))
#carova
lap.botup.carova$LumpTrans=factor(lap.botup.carova$LumpTrans, levels=c("B","UB","U"))
ggplot(lap.botup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,6))
#querub
lap.botup.querub$LumpTrans=factor(lap.botup.querub$LumpTrans, levels=c("B","UB","U"))
ggplot(lap.botup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,6))
##Riparian Bottomland
#acesac
lap.ripbot.acesac$LumpTrans=factor(lap.ripbot.acesac$LumpTrans, levels=c("R","RB","B"))
ggplot(lap.ripbot.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,6))
#carova
lap.ripbot.carova$LumpTrans=factor(lap.ripbot.carova$LumpTrans, levels=c("R","RB","B"))
ggplot(lap.ripbot.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,6))
#querub
lap.ripbot.querub$LumpTrans=factor(lap.ripbot.querub$LumpTrans, levels=c("R","RB","B"))
ggplot(lap.ripbot.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,6))
####nag graph####
##Riparian Upland
#acesac
ggplot(nag.ripup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
#carova
ggplot(nag.ripup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
#querub
ggplot(nag.ripup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
##Bottomland Upland
#acesac
nag.botup.acesac$LumpTrans=factor(nag.botup.acesac$LumpTrans, levels=c("B","UB","U"))
ggplot(nag.botup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
#carova
nag.botup.carova$LumpTrans=factor(nag.botup.carova$LumpTrans, levels=c("B","UB","U"))
ggplot(nag.botup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
#querub
nag.botup.querub$LumpTrans=factor(nag.botup.querub$LumpTrans, levels=c("B","UB","U"))
ggplot(nag.botup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
##Riparian Bottomland
#acesac
nag.ripbot.acesac$LumpTrans=factor(nag.ripbot.acesac$LumpTrans, levels=c("R","RB","B"))
ggplot(nag.ripbot.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
#carova
nag.ripbot.carova$LumpTrans=factor(nag.ripbot.carova$LumpTrans, levels=c("R","RB","B"))
ggplot(nag.ripbot.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
#querub
nag.ripbot.querub$LumpTrans=factor(nag.ripbot.querub$LumpTrans, levels=c("R","RB","B"))
ggplot(nag.ripbot.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,15))
####dopa graph####
##Riparian Upland
#acesac
ggplot(dopa.ripup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
#carova
ggplot(dopa.ripup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
#querub
ggplot(dopa.ripup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
##Bottomland Upland
#acesac
dopa.botup.acesac$LumpTrans=factor(dopa.botup.acesac$LumpTrans, levels=c("B","UB","U"))
ggplot(dopa.botup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
#carova
dopa.botup.carova$LumpTrans=factor(dopa.botup.carova$LumpTrans, levels=c("B","UB","U"))
ggplot(dopa.botup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
#querub
dopa.botup.querub$LumpTrans=factor(dopa.botup.querub$LumpTrans, levels=c("B","UB","U"))
ggplot(dopa.botup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
##Riparian Bottomland
#acesac
dopa.ripbot.acesac$LumpTrans=factor(dopa.ripbot.acesac$LumpTrans, levels=c("R","RB","B"))
ggplot(dopa.ripbot.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
#carova
dopa.ripbot.carova$LumpTrans=factor(dopa.ripbot.carova$LumpTrans, levels=c("R","RB","B"))
ggplot(dopa.ripbot.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
#querub
dopa.ripbot.querub$LumpTrans=factor(dopa.ripbot.querub$LumpTrans, levels=c("R","RB","B"))
ggplot(dopa.ripbot.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
####h2o2 graph####
##Riparian Upland
#acesac
ggplot(h2o2.ripup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
#carova
ggplot(h2o2.ripup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
#querub
ggplot(h2o2.ripup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
##Bottomland Upland
#acesac
h2o2.botup.acesac$LumpTrans=factor(h2o2.botup.acesac$LumpTrans, levels=c("B","UB","U"))
ggplot(h2o2.botup.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
#carova
h2o2.botup.carova$LumpTrans=factor(h2o2.botup.carova$LumpTrans, levels=c("B","UB","U"))
ggplot(h2o2.botup.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
#querub
h2o2.botup.querub$LumpTrans=factor(h2o2.botup.querub$LumpTrans, levels=c("B","UB","U"))
ggplot(h2o2.botup.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
##Riparian Bottomland
#acesac
h2o2.ripbot.acesac$LumpTrans=factor(h2o2.ripbot.acesac$LumpTrans, levels=c("R","RB","B"))
ggplot(h2o2.ripbot.acesac, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
#carova
h2o2.ripbot.carova$LumpTrans=factor(h2o2.ripbot.carova$LumpTrans, levels=c("R","RB","B"))
ggplot(h2o2.ripbot.carova, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
#querub
h2o2.ripbot.querub$LumpTrans=factor(h2o2.ripbot.querub$LumpTrans, levels=c("R","RB","B"))
ggplot(h2o2.ripbot.querub, aes(x=LumpTrans,y=activity.lg,colour=Harvest))+
  geom_boxplot(position=position_dodge(0.9), size=1)+
  #ggtitle("Riparian-Bottomland")  +
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text=element_text(size=30),
        axis.title=element_text(size=30),
        #axis.text.y=element_blank(),
        axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.text = element_text(size=20))+
  ylab("Enzyme activity (nmol/h/g)")+
  scale_y_continuous(limits=c(0,5))
```

```{r enzyme soil rda}
#Merge dopa and hydro datasets with plot design dataset to add the TerrType and ecosys columns.
dopaact.dat.eco=merge(dopaact.dat,plotdesig)
dim(dopaact.dat.eco)
colnames(dopaact.dat.eco)
hydroact.dat.eco=merge(hydroact.dat,plotdesig)
dim(hydroact.dat.eco)
colnames(hydroact.dat.eco)

#dopa enzymes ~ soil variables
#gotta remove some NAs in the soil variables to make this code work.
dopaact.dat.eco=na.exclude(dopaact.dat.eco)
dopa.rda.fulsoil = rda(dopaact.dat.eco[,53], dopaact.dat.eco[,21:45])
anova(dopa.rda.fulsoil)
RsquareAdj(dopa.rda.fulsoil)
global.thresh=RsquareAdj(dopa.rda.fulsoil)$adj.r.squared

dopa.rda.fulsoil.none = rda(dopaact.dat.eco[,53]~1)
dopa.rda.fulsoil = rda(dopaact.dat.eco[,53], dopaact.dat.eco[,21:45])

dopa.rda.fulsoil.full=rda(dopaact.dat.eco[,53]~dopaact.dat.eco$Ptot_long+dopaact.dat.eco$Po_long+dopaact.dat.eco$pH_long+dopaact.dat.eco$moist_long+dopaact.dat.eco$ps1_long+dopaact.dat.eco$ps2_long+dopaact.dat.eco$percc_long+dopaact.dat.eco$cton_long+dopaact.dat.eco$Ptot_nug+dopaact.dat.eco$Po_nug+dopaact.dat.eco$pH_nug+dopaact.dat.eco$moist_nug+dopaact.dat.eco$ps1_nug+dopaact.dat.eco$ps2_nug+dopaact.dat.eco$percc_nug+dopaact.dat.eco$cton_nug+dopaact.dat.eco$Ptot_short+dopaact.dat.eco$Po_short+dopaact.dat.eco$pH_short+dopaact.dat.eco$moist_short +dopaact.dat.eco$ps1_short+dopaact.dat.eco$percc_short+dopaact.dat.eco$cton_short)

dopa.sel=ordiR2step(dopa.rda.fulsoil.none,scope=formula(dopa.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
dopa.sel
#Forward selection picks: pH_long, ps1_nug, percc_short, ptot_short, moist_short

##Check for an ecosystem effect
#dopa enzymes ~ Terr Type
dopa.rda.fulsoil = lm(dopaact.dat.eco[,53]~ dopaact.dat.eco[,2])
anova(dopa.rda.fulsoil)
RsquareAdj(dopa.rda.fulsoil)
global.thresh=RsquareAdj(dopa.rda.fulsoil)$adj.r.squared

##Core+Edge
dopaact.dat.eco=dopaact.dat.eco[dopaact.dat.eco$EP=="Core"|dopaact.dat.eco$EP=="Edge",]
#dopa enzymes ~ soil variables
#gotta remove some NAs in the soil variables to make this code work.
dopaact.dat.eco=na.exclude(dopaact.dat.eco)
dopa.rda.fulsoil = rda(dopaact.dat.eco[,53], dopaact.dat.eco[,21:45])
anova(dopa.rda.fulsoil)
RsquareAdj(dopa.rda.fulsoil)
global.thresh=RsquareAdj(dopa.rda.fulsoil)$adj.r.squared

dopa.rda.fulsoil.none = rda(dopaact.dat.eco[,53]~1)
dopa.rda.fulsoil = rda(dopaact.dat.eco[,53], dopaact.dat.eco[,21:45])

dopa.rda.fulsoil.full=rda(dopaact.dat.eco[,53]~dopaact.dat.eco$Ptot_long+dopaact.dat.eco$Po_long+dopaact.dat.eco$pH_long+dopaact.dat.eco$moist_long+dopaact.dat.eco$ps1_long+dopaact.dat.eco$ps2_long+dopaact.dat.eco$percc_long+dopaact.dat.eco$cton_long+dopaact.dat.eco$Ptot_nug+dopaact.dat.eco$Po_nug+dopaact.dat.eco$pH_nug+dopaact.dat.eco$moist_nug+dopaact.dat.eco$ps1_nug+dopaact.dat.eco$ps2_nug+dopaact.dat.eco$percc_nug+dopaact.dat.eco$cton_nug+dopaact.dat.eco$Ptot_short+dopaact.dat.eco$Po_short+dopaact.dat.eco$pH_short+dopaact.dat.eco$moist_short +dopaact.dat.eco$ps1_short+dopaact.dat.eco$percc_short+dopaact.dat.eco$cton_short)

dopa.sel=ordiR2step(dopa.rda.fulsoil.none,scope=formula(dopa.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
dopa.sel
#Forward selection picks: pH_long, ps1_nug, percc_short, ptot_short, moist_short

##Check for an ecosystem effect
dopa.rda.fulsoil = rda(dopaact.dat.eco[,53], dopaact.dat.eco[,2])
anova(dopa.rda.fulsoil)
RsquareAdj(dopa.rda.fulsoil)
global.thresh=RsquareAdj(dopa.rda.fulsoil)$adj.r.squared

# Hydro enzymes
hydroact.dat=na.exclude(hydroact.dat)
hydro.rda.fulsoil = rda(hydroact.dat[,53], hydroact.dat[,21:45])
anova(hydro.rda.fulsoil)
RsquareAdj(hydro.rda.fulsoil)
global.thresh=RsquareAdj(hydro.rda.fulsoil)$adj.r.squared

hydro.rda.fulsoil.none = rda(hydroact.dat[,53]~1)
hydro.rda.fulsoil = rda(hydroact.dat[,53], hydroact.dat[,21:45])

hydro.rda.fulsoil.full=rda(hydroact.dat[,53]~hydroact.dat$Ptot_long+hydroact.dat$Po_long+hydroact.dat$pH_long+hydroact.dat$moist_long+hydroact.dat$ps1_long+hydroact.dat$ps2_long+hydroact.dat$percc_long+hydroact.dat$cton_long+hydroact.dat$Ptot_nug+hydroact.dat$Po_nug+hydroact.dat$pH_nug+hydroact.dat$moist_nug+hydroact.dat$ps1_nug+hydroact.dat$ps2_nug+hydroact.dat$percc_nug+hydroact.dat$cton_nug+hydroact.dat$Ptot_short+hydroact.dat$Po_short+hydroact.dat$pH_short+hydroact.dat$moist_short +hydroact.dat$ps1_short+hydroact.dat$percc_short+hydroact.dat$cton_short)

hydro.sel=ordiR2step(hydro.rda.fulsoil.none,scope=formula(hydro.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
hydro.sel
#Forward selection: moist_nug, pH_nug, pH_long; ps1_nug

```


```{r enzyme soil mixed model}
####phos####
dim(phos.dat)
phos.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=phos.dat)
anova(phos.soil.mod)

#Check for an ecosystem effect
phos.soil.eco.mod = lm(phos.dat$activity.lg ~ phos.dat$TerrType)
anova(phos.soil.eco.mod)

###CORE###
phos.dat.core=phos.dat[phos.dat$Ecotone!="Ecotone",]
phos.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=phos.dat.core)
anova(phos.soil.mod)

#Check for an ecosystem effect
phos.soil.eco.mod = lm(phos.dat.core$activity.lg ~ phos.dat.core$TerrType)
anova(phos.soil.eco.mod)

##Look at trends
plot(phos.dat.core$activity.lg~phos.dat.core$ps1_long)
plot(phos.dat.core$activity.lg~phos.dat.core$moist_nug)

####bglu####
dim(bglu.dat)
bglu.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=bglu.dat)
anova(bglu.soil.mod)

#Check for an ecosystem effect
bglu.soil.eco.mod = lm(bglu.dat$activity.lg ~ bglu.dat$TerrType)
anova(bglu.soil.eco.mod)

##Check for trends
plot(bglu.dat$activity.lg~bglu.dat$pH_long)
plot(bglu.dat$activity.lg~bglu.dat$moist_short)

###CORE###
bglu.dat.core=bglu.dat[bglu.dat$Ecotone!="Ecotone",]
bglu.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=bglu.dat.core)
anova(bglu.soil.mod)

#Check for an ecosystem effect
bglu.soil.eco.mod = lm(bglu.dat.core$activity.lg ~ bglu.dat.core$TerrType)
anova(bglu.soil.eco.mod)

##Check for trends
plot(bglu.dat.core$activity.lg~bglu.dat.core$pH_long)
plot(bglu.dat.core$activity.lg~bglu.dat.core$moist_short)
plot(bglu.dat.core$activity.lg~bglu.dat.core$moist_nug)

####

####bcell####
dim(bcell.dat)
bcell.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=bcell.dat)
anova(bcell.soil.mod)

#Check for an ecosystem effect
bcell.soil.eco.mod = lm(bcell.dat$activity.lg ~ bcell.dat$TerrType)
anova(bcell.soil.eco.mod)

##Check for trends
plot(bcell.dat$activity.lg~bcell.dat$ps1_long)

###CORE###
bcell.dat.core=bcell.dat[bcell.dat$Ecotone!="Ecotone",]
bcell.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=bcell.dat.core)
anova(bcell.soil.mod)

#Check for an ecosystem effect
bcell.soil.eco.mod = lm(bcell.dat.core$activity.lg ~ bcell.dat.core$TerrType)
anova(bcell.soil.eco.mod)

##Check for trends
plot(bcell.dat.core$activity.lg~bcell.dat.core$ps1_long)

####bxyl####
dim(bxyl.dat)
bxyl.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=bxyl.dat)
anova(bxyl.soil.mod)

#Check for an ecosystem effect
bxyl.soil.eco.mod = lm(bxyl.dat$activity.lg ~ bxyl.dat$TerrType)
anova(bxyl.soil.eco.mod)

###CORE###
bxyl.dat.core=bxyl.dat[bxyl.dat$Ecotone!="Ecotone",]
bxyl.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=bxyl.dat.core)
anova(bxyl.soil.mod)

#Check for an ecosystem effect
bxyl.soil.eco.mod = lm(bxyl.dat.core$activity.lg ~ bxyl.dat.core$TerrType)
anova(bxyl.soil.eco.mod)

####lap####
dim(lap.dat)
lap.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=lap.dat)
anova(lap.soil.mod)

#Check for an ecosystem effect
lap.soil.eco.mod = lm(lap.dat$activity.lg ~ lap.dat$TerrType)
anova(lap.soil.eco.mod)

###CORE###
lap.dat.core=lap.dat[lap.dat$Ecotone!="Ecotone",]
lap.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=lap.dat.core)
anova(lap.soil.mod)

#Check for an ecosystem effect
lap.soil.eco.mod = lm(lap.dat.core$activity.lg ~ lap.dat.core$TerrType)
anova(lap.soil.eco.mod)

####nag####
dim(nag.dat)
nag.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=nag.dat)
anova(nag.soil.mod)

#Check for an ecosystem effect
nag.soil.eco.mod = lm(nag.dat$activity.lg ~ nag.dat$TerrType)
anova(nag.soil.eco.mod)

###CORE###
nag.dat.core=nag.dat[nag.dat$Ecotone!="Ecotone",]
nag.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=nag.dat.core)
anova(nag.soil.mod)

#Check for an ecosystem effect
nag.soil.eco.mod = lm(nag.dat.core$activity.lg ~ nag.dat.core$TerrType)
anova(nag.soil.eco.mod)

####dopa####
dim(dopa.dat)
dopa.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=dopa.dat)
anova(dopa.soil.mod)

#Check for an ecosystem effect
dopa.soil.eco.mod = lm(dopa.dat$activity.lg ~ dopa.dat$TerrType)
anova(dopa.soil.eco.mod)

###CORE###
dopa.dat.core=dopa.dat[dopa.dat$Ecotone!="Ecotone",]
dopa.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=dopa.dat.core)
anova(dopa.soil.mod)

#Check for an ecosystem effect
dopa.soil.eco.mod = lm(dopa.dat.core$activity.lg ~ dopa.dat.core$TerrType)
anova(dopa.soil.eco.mod)

####h2o2####
dim(h2o2.dat)
h2o2.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=h2o2.dat)
anova(h2o2.soil.mod)

#Check for an ecosystem effect
h2o2.soil.eco.mod = lm(h2o2.dat$activity.lg ~ h2o2.dat$TerrType)
anova(h2o2.soil.eco.mod)

##Check for trends
plot(h2o2.dat$activity.lg~h2o2.dat$Ptot_long)
plot(h2o2.dat$activity.lg~h2o2.dat$pH_long)
plot(h2o2.dat$activity.lg~h2o2.dat$ps1_nug)

###CORE###
h2o2.dat.core=h2o2.dat[h2o2.dat$Ecotone!="Ecotone",]
h2o2.soil.mod=lme(activity.lg~Ptot_long+Po_long+pH_long+moist_long +ps1_long+ps2_long+percc_long+cton_long+Ptot_short+Po_short+pH_short+moist_short +ps1_short+percc_short+cton_short+Ptot_nug+Po_nug+pH_nug+moist_nug +ps1_nug+percc_nug+cton_nug,random=~1|Plot, data=h2o2.dat.core)
anova(h2o2.soil.mod)

#Check for an ecosystem effect
h2o2.soil.eco.mod = lm(h2o2.dat.core$activity.lg ~ h2o2.dat.core$TerrType)
anova(h2o2.soil.eco.mod)

##Check for trends
plot(h2o2.dat.core$activity.lg~h2o2.dat.core$Ptot_long)
plot(h2o2.dat.core$activity.lg~h2o2.dat.core$pH_long)
```