---
title: "Leaf Chemistry Analyses"
author: "Colleen"
date: "12/14/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load data}
leafchem=read.csv("leafchemcalcs.csv", header=TRUE)
dim(leafchem)
#Because of the highlighting and stuff in the excel file, there are extra rows. Cut them out
leafchem=leafchem[1:8,]
##CAROVA T03 is an outlier because I fucked up that sample - we'll just cut it out now so it doesn't screw up the analyses.

lig.n=read.csv("costech.data.csv",header=TRUE)

###libraries
library(ggpubr)
library(stats)
library(nlme)
```


```{r stats}
##non-polar extractives
order=factor(leafchem$species, levels=c("carova", "acesac","querub"))
colnames(leafchem)
npe=aov(leafchem$prop.nonpolar.extract..ash.free.~leafchem$species)
summary(npe)
shapiro.test(leafchem$prop.nonpolar.extract..ash.free.)
ggqqplot(leafchem$prop.nonpolar.extract..ash.free.)
boxplot(leafchem$prop.nonpolar.extract..ash.free.~order, main="Non-polar Extractives", ylab="NPE conc", xlab="Species")

##polar extractives
pe=aov(leafchem$prop.polar.extract..ash.free.~leafchem$species)
summary(pe)
shapiro.test(leafchem$prop.polar.extract..ash.free.)
TukeyHSD(pe)
boxplot(leafchem$prop.polar.extract..ash.free.~order, main="Polar Extractives", ylab="PE conc", xlab="Species")

##acid-hydrolysable compounds
ahc=aov(leafchem$prop.AH.cell.wall.compds..ash.free.~leafchem$species)
summary(ahc)
shapiro.test(leafchem$prop.AH.cell.wall.compds..ash.free.)
TukeyHSD(ahc)
boxplot(leafchem$prop.AH.cell.wall.compds..ash.free.~order, main="Acid Hydrolysable", ylab="AH conc", xlab="Species")

##non-acid hydrolysable compounds
nahc=aov(leafchem$prop.NAH.cell.wall.compds..ash.free.~leafchem$species)
summary(nahc)
shapiro.test(leafchem$prop.NAH.cell.wall.compds..ash.free.)
TukeyHSD(nahc)
boxplot(leafchem$prop.NAH.cell.wall.compds..ash.free.~order,main="Non-Acid Hydrolysable",ylab="NAH conc", xlab="Species")

###Costech Stats
##C:N
order=factor(lig.n$Species, levels=c("CAROVA", "ACESAC","QUERUB"))
colnames(lig.n)
cton=aov(lig.n$C.N~lig.n$Species)
summary(cton)
shapiro.test(lig.n$C.N)
ggqqplot(lig.n$C.N)
boxplot(lig.n$C.N~order, main="C:N", ylab="C:N", xlab="Species")

##NAH:N
chem=merge(leafchem, lig.n)
dim(chem)

nah.n=aov(chem$prop.nonpolar.extract..ash.free.~chem$Nitrogen)
summary(nah.n)
ggplot(chem, aes(x=Nitrogen, y=prop.NAH.cell.wall.compds..ash.free., color=species))+
  geom_point(size=4)+
  theme_bw()
```




```{r sd}
acesac=leafchem[leafchem$species=="acesac",]
sd(acesac$Polar.Extracts)
sd(acesac$Non.Polar.Extracts)
sd(acesac$prop.AH.cell.wall.compds..ash.free.)
sd(acesac$prop.NAH.cell.wall.compds..ash.free.)

acesac.n=lig.n[lig.n$Species=="ACESAC",]
sd(acesac.n$C.N)


carova=leafchem[leafchem$species=="carova",]
sd(carova$Polar.Extracts)
sd(carova$Non.Polar.Extracts)
sd(carova$prop.AH.cell.wall.compds..ash.free.)
sd(carova$prop.NAH.cell.wall.compds..ash.free.)

carova.n=lig.n[lig.n$Species=="CAROVA",]
sd(carova.n$C.N)

querub=leafchem[leafchem$species=="querub",]
sd(querub$Polar.Extracts)
sd(querub$Non.Polar.Extracts)
sd(querub$prop.AH.cell.wall.compds..ash.free.)
sd(querub$prop.NAH.cell.wall.compds..ash.free.)

querub.n=lig.n[lig.n$Species=="QUERUB",]
sd(querub.n$C.N)

```